///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Drop_down_Qualcheck_test
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AQMC_redux recording.
    /// </summary>
    [TestModule("0a25b455-b950-4077-98c3-fb5cf56714a7", ModuleType.Recording, 1)]
    public partial class AQMC_redux : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Drop_down_Qualcheck_testRepository repository.
        /// </summary>
        public static Drop_down_Qualcheck_testRepository repo = Drop_down_Qualcheck_testRepository.Instance;

        static AQMC_redux instance = new AQMC_redux();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AQMC_redux()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AQMC_redux Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 150;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 2.00;

            Init();

            Report.Log(ReportLevel.Info, "Application", "Run application 'C:\\Users\\Sunjeet.Khokhar\\Desktop\\AQ Mobile Collect.nal' with arguments '' in normal mode.", new RecordItemIndex(0));
            Host.Local.RunApplication("C:\\Users\\Sunjeet.Khokhar\\Desktop\\AQ Mobile Collect.nal", "", "C:\\Users\\Sunjeet.Khokhar\\Desktop", false);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AQMC.AQMC' at 231;54.", repo.AQMC.AQMCInfo, new RecordItemIndex(1));
            repo.AQMC.AQMC.Click("231;54");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(2));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AQMC.AQMC' at 152;188.", repo.AQMC.AQMCInfo, new RecordItemIndex(3));
            repo.AQMC.AQMC.Click("152;188");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(4));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AQMC.AQMC' at 161;56.", repo.AQMC.AQMCInfo, new RecordItemIndex(5));
            repo.AQMC.AQMC.Click("161;56");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(6));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AQMC.AQMC' at 139;54.", repo.AQMC.AQMCInfo, new RecordItemIndex(7));
            repo.AQMC.AQMC.Click("139;54");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'AQMC.AQMC' at 1595;371.", repo.AQMC.AQMCInfo, new RecordItemIndex(8));
            repo.AQMC.AQMC.MoveTo("1595;371");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(9));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'AQMC.AQMC' at 1594;478.", repo.AQMC.AQMCInfo, new RecordItemIndex(10));
            repo.AQMC.AQMC.MoveTo("1594;478");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(11));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AQMC.AQMC' at 145;439.", repo.AQMC.AQMCInfo, new RecordItemIndex(12));
            repo.AQMC.AQMC.Click("145;439");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(13));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}{Back}{Back}' with focus on 'AQMC.AQMC'.", repo.AQMC.AQMCInfo, new RecordItemIndex(14));
            repo.AQMC.AQMC.PressKeys("{Back}{Back}{Back}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '888' with focus on 'AQMC.AQMC'.", repo.AQMC.AQMCInfo, new RecordItemIndex(15));
            repo.AQMC.AQMC.PressKeys("888");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AQMC.AQMC' at 134;494.", repo.AQMC.AQMCInfo, new RecordItemIndex(16));
            repo.AQMC.AQMC.Click("134;494");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}{Back}{Back}666' with focus on 'AQMC.AQMC'.", repo.AQMC.AQMCInfo, new RecordItemIndex(17));
            repo.AQMC.AQMC.PressKeys("{Back}{Back}{Back}666");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'AQMC.AQMC' at 1594;422.", repo.AQMC.AQMCInfo, new RecordItemIndex(18));
            repo.AQMC.AQMC.MoveTo("1594;422");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'AQMC.AQMC' at 1607;624.", repo.AQMC.AQMCInfo, new RecordItemIndex(19));
            repo.AQMC.AQMC.MoveTo("1607;624");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AQMC.AQMC' at 423;540.", repo.AQMC.AQMCInfo, new RecordItemIndex(20));
            repo.AQMC.AQMC.Click("423;540");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'script' with focus on 'AQMC.AQMC'.", repo.AQMC.AQMCInfo, new RecordItemIndex(21));
            repo.AQMC.AQMC.PressKeys("script");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'AQMC.AQMC' at 1596;502.", repo.AQMC.AQMCInfo, new RecordItemIndex(22));
            repo.AQMC.AQMC.MoveTo("1596;502");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'AQMC.AQMC' at 1607;645.", repo.AQMC.AQMCInfo, new RecordItemIndex(23));
            repo.AQMC.AQMC.MoveTo("1607;645");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AQMC.AQMC' at 55;586.", repo.AQMC.AQMCInfo, new RecordItemIndex(24));
            repo.AQMC.AQMC.Click("55;586");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'AQMC.AQMC' at 1598;653.", repo.AQMC.AQMCInfo, new RecordItemIndex(25));
            repo.AQMC.AQMC.MoveTo("1598;653");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'AQMC.AQMC' at 1602;698.", repo.AQMC.AQMCInfo, new RecordItemIndex(26));
            repo.AQMC.AQMC.MoveTo("1602;698");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AQMC.AQMC' at 64;744.", repo.AQMC.AQMCInfo, new RecordItemIndex(27));
            repo.AQMC.AQMC.Click("64;744");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AQMC.AQMC' at 1200;843.", repo.AQMC.AQMCInfo, new RecordItemIndex(28));
            repo.AQMC.AQMC.Click("1200;843");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'AQMC.AQMC' at 1595;220.", repo.AQMC.AQMCInfo, new RecordItemIndex(29));
            repo.AQMC.AQMC.MoveTo("1595;220");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'AQMC.AQMC' at 1594;243.", repo.AQMC.AQMCInfo, new RecordItemIndex(30));
            repo.AQMC.AQMC.MoveTo("1594;243");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AQMC.AQMC' at 60;305.", repo.AQMC.AQMCInfo, new RecordItemIndex(31));
            repo.AQMC.AQMC.Click("60;305");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AQMC.AQMC' at 72;482.", repo.AQMC.AQMCInfo, new RecordItemIndex(32));
            repo.AQMC.AQMC.Click("72;482");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'script' with focus on 'AQMC.AQMC'.", repo.AQMC.AQMCInfo, new RecordItemIndex(33));
            repo.AQMC.AQMC.PressKeys("script");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AQMC.AQMC' at 562;660.", repo.AQMC.AQMCInfo, new RecordItemIndex(34));
            repo.AQMC.AQMC.Click("562;660");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'test123' with focus on 'AQMC.AQMC'.", repo.AQMC.AQMCInfo, new RecordItemIndex(35));
            repo.AQMC.AQMC.PressKeys("test123");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back 9}123' with focus on 'AQMC.AQMC'.", repo.AQMC.AQMCInfo, new RecordItemIndex(36));
            repo.AQMC.AQMC.PressKeys("{Back 9}123");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'AQMC.AQMC' at 1595;248.", repo.AQMC.AQMCInfo, new RecordItemIndex(37));
            repo.AQMC.AQMC.MoveTo("1595;248");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'AQMC.AQMC' at 1599;454.", repo.AQMC.AQMCInfo, new RecordItemIndex(38));
            repo.AQMC.AQMC.MoveTo("1599;454");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AQMC.AQMC' at 127;343.", repo.AQMC.AQMCInfo, new RecordItemIndex(39));
            repo.AQMC.AQMC.Click("127;343");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}111' with focus on 'AQMC.AQMC'.", repo.AQMC.AQMCInfo, new RecordItemIndex(40));
            repo.AQMC.AQMC.PressKeys("{Back}111");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AQMC.AQMC' at 51;407.", repo.AQMC.AQMCInfo, new RecordItemIndex(41));
            repo.AQMC.AQMC.Click("51;407");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AQMC.AQMC' at 51;489.", repo.AQMC.AQMCInfo, new RecordItemIndex(42));
            repo.AQMC.AQMC.Click("51;489");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AQMC.AQMC' at 61;681.", repo.AQMC.AQMCInfo, new RecordItemIndex(43));
            repo.AQMC.AQMC.Click("61;681");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'AQMC.AQMC' at 1597;448.", repo.AQMC.AQMCInfo, new RecordItemIndex(44));
            repo.AQMC.AQMC.MoveTo("1597;448");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'AQMC.AQMC' at 1596;520.", repo.AQMC.AQMCInfo, new RecordItemIndex(45));
            repo.AQMC.AQMC.MoveTo("1596;520");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AQMC.AQMC' at 53;283.", repo.AQMC.AQMCInfo, new RecordItemIndex(46));
            repo.AQMC.AQMC.Click("53;283");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AQMC.AQMC' at 54;639.", repo.AQMC.AQMCInfo, new RecordItemIndex(47));
            repo.AQMC.AQMC.Click("54;639");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'AQMC.AQMC' at 1596;511.", repo.AQMC.AQMCInfo, new RecordItemIndex(48));
            repo.AQMC.AQMC.MoveTo("1596;511");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'AQMC.AQMC' at 1597;680.", repo.AQMC.AQMCInfo, new RecordItemIndex(49));
            repo.AQMC.AQMC.MoveTo("1597;680");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AQMC.AQMC' at 58;261.", repo.AQMC.AQMCInfo, new RecordItemIndex(50));
            repo.AQMC.AQMC.Click("58;261");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AQMC.AQMC' at 50;436.", repo.AQMC.AQMCInfo, new RecordItemIndex(51));
            repo.AQMC.AQMC.Click("50;436");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'AQMC.AQMC' at 1593;652.", repo.AQMC.AQMCInfo, new RecordItemIndex(52));
            repo.AQMC.AQMC.MoveTo("1593;652");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AQMC.AQMC' at 58;260.", repo.AQMC.AQMCInfo, new RecordItemIndex(53));
            repo.AQMC.AQMC.Click("58;260");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'AQMC.AQMC' at 1594;743.", repo.AQMC.AQMCInfo, new RecordItemIndex(54));
            repo.AQMC.AQMC.MoveTo("1594;743");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AQMC.AQMC' at 1175;838.", repo.AQMC.AQMCInfo, new RecordItemIndex(55));
            repo.AQMC.AQMC.Click("1175;838");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
