///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Drop_down_Qualcheck_test
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AQMC_triux recording.
    /// </summary>
    [TestModule("f0c0e421-a9b7-46fd-8e1b-38c4d5fcc6ee", ModuleType.Recording, 1)]
    public partial class AQMC_triux : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Drop_down_Qualcheck_testRepository repository.
        /// </summary>
        public static Drop_down_Qualcheck_testRepository repo = Drop_down_Qualcheck_testRepository.Instance;

        static AQMC_triux instance = new AQMC_triux();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AQMC_triux()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AQMC_triux Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 600;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 0.50;

            Init();

            Report.Log(ReportLevel.Info, "Application", "Run application 'C:\\Users\\Sunjeet.Khokhar\\Desktop\\AQ Mobile Collect.nal' with arguments '' in normal mode.", new RecordItemIndex(0));
            Host.Local.RunApplication("C:\\Users\\Sunjeet.Khokhar\\Desktop\\AQ Mobile Collect.nal", "", "C:\\Users\\Sunjeet.Khokhar\\Desktop", false);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AQMC.AQMC' at 234;56.", repo.AQMC.AQMCInfo, new RecordItemIndex(1));
            repo.AQMC.AQMC.Click("234;56");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AQMC.AQMC' at 165;131.", repo.AQMC.AQMCInfo, new RecordItemIndex(2));
            repo.AQMC.AQMC.Click("165;131");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AQMC.AQMC' at 159;60.", repo.AQMC.AQMCInfo, new RecordItemIndex(3));
            repo.AQMC.AQMC.Click("159;60");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AQMC.AQMC' at 140;53.", repo.AQMC.AQMCInfo, new RecordItemIndex(4));
            repo.AQMC.AQMC.Click("140;53");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AQMC.AQMC' at 120;763.", repo.AQMC.AQMCInfo, new RecordItemIndex(5));
            repo.AQMC.AQMC.Click("120;763");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AQMC.AQMC' at 120;763.", repo.AQMC.AQMCInfo, new RecordItemIndex(6));
            repo.AQMC.AQMC.Click("120;763");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}344' with focus on 'AQMC.AQMC'.", repo.AQMC.AQMCInfo, new RecordItemIndex(7));
            repo.AQMC.AQMC.PressKeys("{Back}344");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AQMC.AQMC' at 1186;838.", repo.AQMC.AQMCInfo, new RecordItemIndex(8));
            repo.AQMC.AQMC.Click("1186;838");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck6.Button2' at 33;8.", repo.Qualcheck6.Button2Info, new RecordItemIndex(9));
            repo.Qualcheck6.Button2.Click("33;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AQMC.AQMC' at 199;50.", repo.AQMC.AQMCInfo, new RecordItemIndex(10));
            repo.AQMC.AQMC.Click("199;50");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck6.RawTextYes' at 3;11.", repo.Qualcheck6.RawTextYesInfo, new RecordItemIndex(11));
            repo.Qualcheck6.RawTextYes.Click("3;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AQMC.Close' at 19;11.", repo.AQMC.CloseInfo, new RecordItemIndex(12));
            repo.AQMC.Close.Click("19;11");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
