///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Drop_down_Qualcheck_test
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AQMC recording.
    /// </summary>
    [TestModule("dbbf6b44-8f2d-417f-8358-6f0d5eec071b", ModuleType.Recording, 1)]
    public partial class AQMC : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Drop_down_Qualcheck_testRepository repository.
        /// </summary>
        public static Drop_down_Qualcheck_testRepository repo = Drop_down_Qualcheck_testRepository.Instance;

        static AQMC instance = new AQMC();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AQMC()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AQMC Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Application", "Run application 'C:\\Users\\Sunjeet.Khokhar\\Desktop\\AQ Mobile Collect.nal' with arguments '' in normal mode.", new RecordItemIndex(0));
            Host.Local.RunApplication("C:\\Users\\Sunjeet.Khokhar\\Desktop\\AQ Mobile Collect.nal", "", "C:\\Users\\Sunjeet.Khokhar\\Desktop", false);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AQMC.AQMC' at 231;54.", repo.AQMC.AQMCInfo, new RecordItemIndex(1));
            repo.AQMC.AQMC.Click("231;54");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AQMC.AQMC' at 170;57.", repo.AQMC.AQMCInfo, new RecordItemIndex(2));
            repo.AQMC.AQMC.Click("170;57");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AQMC.AQMC' at 166;139.", repo.AQMC.AQMCInfo, new RecordItemIndex(3));
            repo.AQMC.AQMC.Click("166;139");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AQMC.AQMC' at 155;41.", repo.AQMC.AQMCInfo, new RecordItemIndex(4));
            repo.AQMC.AQMC.Click("155;41");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AQMC.AQMC' at 137;48.", repo.AQMC.AQMCInfo, new RecordItemIndex(5));
            repo.AQMC.AQMC.Click("137;48");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AQMC.AQMC' at 130;750.", repo.AQMC.AQMCInfo, new RecordItemIndex(6));
            repo.AQMC.AQMC.Click("130;750");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}123' with focus on 'AQMC.AQMC'.", repo.AQMC.AQMCInfo, new RecordItemIndex(7));
            repo.AQMC.AQMC.PressKeys("{Back}123");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AQMC.AQMC' at 1206;833.", repo.AQMC.AQMCInfo, new RecordItemIndex(8));
            repo.AQMC.AQMC.Click("1206;833");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck6.Button2' at 22;16.", repo.Qualcheck6.Button2Info, new RecordItemIndex(9));
            repo.Qualcheck6.Button2.Click("22;16");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AQMC.AQMC' at 248;55.", repo.AQMC.AQMCInfo, new RecordItemIndex(10));
            repo.AQMC.AQMC.Click("248;55");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck6.Button6' at 9;12.", repo.Qualcheck6.Button6Info, new RecordItemIndex(11));
            repo.Qualcheck6.Button6.Click("9;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AQMC.Close' at 7;0.", repo.AQMC.CloseInfo, new RecordItemIndex(12));
            repo.AQMC.Close.Click("7;0");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
