///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Drop_down_Qualcheck_test
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AuditTrax_job_search_and_processing recording.
    /// </summary>
    [TestModule("d498f0de-b3ad-457d-ba04-8e4e452e5940", ModuleType.Recording, 1)]
    public partial class AuditTrax_job_search_and_processing : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Drop_down_Qualcheck_testRepository repository.
        /// </summary>
        public static Drop_down_Qualcheck_testRepository repo = Drop_down_Qualcheck_testRepository.Instance;

        static AuditTrax_job_search_and_processing instance = new AuditTrax_job_search_and_processing();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AuditTrax_job_search_and_processing()
        {
            Dummy_var = "";
            User_Name = "cliffordt{Tab}";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AuditTrax_job_search_and_processing Instance
        {
            get { return instance; }
        }

#region Variables

        string _Dummy_var;

        /// <summary>
        /// Gets or sets the value of variable Dummy_var.
        /// </summary>
        [TestVariable("d3cf9108-f1e2-4ba4-aa00-7fae41dc13d1")]
        public string Dummy_var
        {
            get { return _Dummy_var; }
            set { _Dummy_var = value; }
        }

        string _User_Name;

        /// <summary>
        /// Gets or sets the value of variable User_Name.
        /// </summary>
        [TestVariable("3e93453f-2671-4f29-8840-6d63eccabbcb")]
        public string User_Name
        {
            get { return _User_Name; }
            set { _User_Name = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable index.
        /// </summary>
        [TestVariable("3d9a6b1a-8570-47ad-95bb-be9fa81d20e2")]
        public string index
        {
            get { return repo.index; }
            set { repo.index = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable InnerText.
        /// </summary>
        [TestVariable("311b8acd-44e7-4b2a-8bd6-55e023ba8297")]
        public string InnerText
        {
            get { return repo.InnerText; }
            set { repo.InnerText = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'https://cftest.asurequality.com/audittrax/Login.cfm' with browser 'chrome' in normal mode.", new RecordItemIndex(0));
            Host.Local.OpenBrowser("https://cftest.asurequality.com/audittrax/Login.cfm", "chrome", "", false, false, false, false, false);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AuditTraxAsureQualitysAuditTracking.MenuTitles' at 48;4.", repo.AuditTraxAsureQualitysAuditTracking.MenuTitlesInfo, new RecordItemIndex(1));
            repo.AuditTraxAsureQualitysAuditTracking.MenuTitles.Click("48;4");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AuditTraxAsureQualitysAuditTracking.SomeTableTag.ClientContact' at 7;7.", repo.AuditTraxAsureQualitysAuditTracking.SomeTableTag.ClientContactInfo, new RecordItemIndex(2));
            repo.AuditTraxAsureQualitysAuditTracking.SomeTableTag.ClientContact.Click("7;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'cliffordt{Tab}' with focus on 'AuditTraxAsureQualitysAuditTracking.SomeTableTag.ClientContact'.", repo.AuditTraxAsureQualitysAuditTracking.SomeTableTag.ClientContactInfo, new RecordItemIndex(3));
            repo.AuditTraxAsureQualitysAuditTracking.SomeTableTag.ClientContact.PressKeys("cliffordt{Tab}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AuditTraxAsureQualitysAuditTracking.SomeTableTag.MenuTitles1' at 48;6.", repo.AuditTraxAsureQualitysAuditTracking.SomeTableTag.MenuTitles1Info, new RecordItemIndex(4));
            repo.AuditTraxAsureQualitysAuditTracking.SomeTableTag.MenuTitles1.Click("48;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AuditTraxAsureQualitysAuditTracking.SomeTableTag.ClientPassword' at 9;11.", repo.AuditTraxAsureQualitysAuditTracking.SomeTableTag.ClientPasswordInfo, new RecordItemIndex(5));
            repo.AuditTraxAsureQualitysAuditTracking.SomeTableTag.ClientPassword.Click("9;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'qualcheck' with focus on 'AuditTraxAsureQualitysAuditTracking.SomeTableTag.ClientPassword'.", repo.AuditTraxAsureQualitysAuditTracking.SomeTableTag.ClientPasswordInfo, new RecordItemIndex(6));
            repo.AuditTraxAsureQualitysAuditTracking.SomeTableTag.ClientPassword.PressKeys("qualcheck");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AuditTraxAsureQualitysAuditTracking.FmtButtons' at 29;15.", repo.AuditTraxAsureQualitysAuditTracking.FmtButtonsInfo, new RecordItemIndex(7));
            repo.AuditTraxAsureQualitysAuditTracking.FmtButtons.Click("29;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'AuditTraxAsureQualitysAuditTracking.UserInfo'.", repo.AuditTraxAsureQualitysAuditTracking.UserInfoInfo, new RecordItemIndex(8));
            Validate.Exists(repo.AuditTraxAsureQualitysAuditTracking.UserInfoInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AuditTraxAsureQualitysAuditTracking.SomeTableTag1' at 36;43.", repo.AuditTraxAsureQualitysAuditTracking.SomeTableTag1Info, new RecordItemIndex(9));
            repo.AuditTraxAsureQualitysAuditTracking.SomeTableTag1.Click("36;43");
            Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AuditTraxAsureQualitysAuditTracking.SomeTableTag2.Specalt3' at 48;15.", repo.AuditTraxAsureQualitysAuditTracking.SomeTableTag2.Specalt3Info, new RecordItemIndex(10));
            //repo.AuditTraxAsureQualitysAuditTracking.SomeTableTag2.Specalt3.Click("48;15");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AuditTraxAsureQualitysAuditTracking.SomeTableTag2.FontTag386802' at .25;.25.", repo.AuditTraxAsureQualitysAuditTracking.SomeTableTag2.FontTag386802Info, new RecordItemIndex(11));
            //repo.AuditTraxAsureQualitysAuditTracking.SomeTableTag2.FontTag386802.Click(".25;.25");
            //Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AuditTraxAsureQualitysAuditTracking.SomeTableTag2.Task386792BookAssignedGif' at 32;0.", repo.AuditTraxAsureQualitysAuditTracking.SomeTableTag2.Task386792BookAssignedGifInfo, new RecordItemIndex(12));
            repo.AuditTraxAsureQualitysAuditTracking.SomeTableTag2.Task386792BookAssignedGif.Click("32;0");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(13));
            Delay.Duration(3000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AuditTraxAsureQualitysAuditTracking.ReturnToList' at 77;10.", repo.AuditTraxAsureQualitysAuditTracking.ReturnToListInfo, new RecordItemIndex(14));
            repo.AuditTraxAsureQualitysAuditTracking.ReturnToList.Click("77;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AuditTraxAsureQualitysAuditTracking.Logout' at 37;13.", repo.AuditTraxAsureQualitysAuditTracking.LogoutInfo, new RecordItemIndex(15));
            repo.AuditTraxAsureQualitysAuditTracking.Logout.Click("37;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AuditTraxAsureQualitysAuditTracking.ContentDisplay' at 505;271.", repo.AuditTraxAsureQualitysAuditTracking.ContentDisplayInfo, new RecordItemIndex(16));
            repo.AuditTraxAsureQualitysAuditTracking.ContentDisplay.Click("505;271");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AuditTraxAsureQualitysAuditTracking1.Client' at 991;5.", repo.AuditTraxAsureQualitysAuditTracking1.ClientInfo, new RecordItemIndex(17));
            repo.AuditTraxAsureQualitysAuditTracking1.Client.Click("991;5");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
