///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Drop_down_Qualcheck_test
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("ed4827a2-8c65-4820-9e21-316042259ea6", ModuleType.Recording, 1)]
    public partial class Base_recording_to_re_use : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Drop_down_Qualcheck_testRepository repository.
        /// </summary>
        public static Drop_down_Qualcheck_testRepository repo = Drop_down_Qualcheck_testRepository.Instance;

        static Base_recording_to_re_use instance = new Base_recording_to_re_use();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Base_recording_to_re_use()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Base_recording_to_re_use Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck5.Button1004' at 85;5.", repo.Qualcheck5.Button1004Info, new RecordItemIndex(0));
            repo.Qualcheck5.Button1004.Click("85;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck4.RadioButton2' at 9;11.", repo.Qualcheck4.RadioButton2Info, new RecordItemIndex(1));
            repo.Qualcheck4.RadioButton2.Click("9;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck4.TextT12' at 150;1.", repo.Qualcheck4.TextT12Info, new RecordItemIndex(2));
            repo.Qualcheck4.TextT12.Click("150;1");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck4.ListItemNZGAPManualNumber' at 223;10.", repo.Qualcheck4.ListItemNZGAPManualNumberInfo, new RecordItemIndex(3));
            repo.Qualcheck4.ListItemNZGAPManualNumber.Click("223;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck3.LineDown' at 5;13.", repo.Qualcheck3.LineDownInfo, new RecordItemIndex(4));
            repo.Qualcheck3.LineDown.Click("5;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck3.LineDown' at 5;13.", repo.Qualcheck3.LineDownInfo, new RecordItemIndex(5));
            repo.Qualcheck3.LineDown.Click("5;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck3.LineDown' at 5;13.", repo.Qualcheck3.LineDownInfo, new RecordItemIndex(6));
            repo.Qualcheck3.LineDown.Click("5;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck3.LineDown' at 5;13.", repo.Qualcheck3.LineDownInfo, new RecordItemIndex(7));
            repo.Qualcheck3.LineDown.Click("5;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck3.LineDown' at 5;13.", repo.Qualcheck3.LineDownInfo, new RecordItemIndex(8));
            repo.Qualcheck3.LineDown.Click("5;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck3.LineDown' at 5;13.", repo.Qualcheck3.LineDownInfo, new RecordItemIndex(9));
            repo.Qualcheck3.LineDown.Click("5;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck3.LineDown' at 5;13.", repo.Qualcheck3.LineDownInfo, new RecordItemIndex(10));
            repo.Qualcheck3.LineDown.Click("5;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck3.LineDown' at 5;13.", repo.Qualcheck3.LineDownInfo, new RecordItemIndex(11));
            repo.Qualcheck3.LineDown.Click("5;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck3.LineDown' at 5;13.", repo.Qualcheck3.LineDownInfo, new RecordItemIndex(12));
            repo.Qualcheck3.LineDown.Click("5;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck3.LineDown' at 5;13.", repo.Qualcheck3.LineDownInfo, new RecordItemIndex(13));
            repo.Qualcheck3.LineDown.Click("5;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck3.LineDown' at 5;13.", repo.Qualcheck3.LineDownInfo, new RecordItemIndex(14));
            repo.Qualcheck3.LineDown.Click("5;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck3.LineDown' at 5;13.", repo.Qualcheck3.LineDownInfo, new RecordItemIndex(15));
            repo.Qualcheck3.LineDown.Click("5;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck3.LineDown' at 5;13.", repo.Qualcheck3.LineDownInfo, new RecordItemIndex(16));
            repo.Qualcheck3.LineDown.Click("5;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck3.LineDown' at 5;13.", repo.Qualcheck3.LineDownInfo, new RecordItemIndex(17));
            repo.Qualcheck3.LineDown.Click("5;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck3' at 139;176.", repo.Qualcheck3.SelfInfo, new RecordItemIndex(18));
            repo.Qualcheck3.Self.Click("139;176");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck4.TextT13' at 61;4.", repo.Qualcheck4.TextT13Info, new RecordItemIndex(19));
            repo.Qualcheck4.TextT13.Click("61;4");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '3'.", new RecordItemIndex(20));
            Keyboard.Press("3");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck4.JobTypeT' at 78;8.", repo.Qualcheck4.JobTypeTInfo, new RecordItemIndex(21));
            repo.Qualcheck4.JobTypeT.Click("78;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck4.JobType' at 226;7.", repo.Qualcheck4.JobTypeInfo, new RecordItemIndex(22));
            repo.Qualcheck4.JobType.Click("226;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck3' at 199;16.", repo.Qualcheck3.SelfInfo, new RecordItemIndex(23));
            repo.Qualcheck3.Self.Click("199;16");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Down}'.", new RecordItemIndex(24));
            Keyboard.Press("{Down}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck4.TextT4' at 86;13.", repo.Qualcheck4.TextT4Info, new RecordItemIndex(25));
            repo.Qualcheck4.TextT4.Click("86;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck4.OfficeId' at 94;9.", repo.Qualcheck4.OfficeIdInfo, new RecordItemIndex(26));
            repo.Qualcheck4.OfficeId.Click("94;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck3' at 94;8.", repo.Qualcheck3.SelfInfo, new RecordItemIndex(27));
            repo.Qualcheck3.Self.Click("94;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck4.Button1004' at 47;12.", repo.Qualcheck4.Button1004Info, new RecordItemIndex(28));
            repo.Qualcheck4.Button1004.Click("47;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck6.Button6' at 33;8.", repo.Qualcheck6.Button6Info, new RecordItemIndex(29));
            repo.Qualcheck6.Button6.Click("33;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Explorer.RanorexStudio' at 39;11.", repo.Explorer.RanorexStudioInfo, new RecordItemIndex(30));
            repo.Explorer.RanorexStudio.Click("39;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Explorer1.DropDownQualcheckTestRanorexStudi' at 50;119.", repo.Explorer1.DropDownQualcheckTestRanorexStudiInfo, new RecordItemIndex(31));
            repo.Explorer1.DropDownQualcheckTestRanorexStudi.Click("50;119");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Explorer.RanorexStudio' at 42;1.", repo.Explorer.RanorexStudioInfo, new RecordItemIndex(32));
            repo.Explorer.RanorexStudio.Click("42;1");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Explorer1.DropDownQualcheckTestRanorexStudi' at 60;119.", repo.Explorer1.DropDownQualcheckTestRanorexStudiInfo, new RecordItemIndex(33));
            repo.Explorer1.DropDownQualcheckTestRanorexStudi.Click("60;119");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
