///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Drop_down_Qualcheck_test
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording2 recording.
    /// </summary>
    [TestModule("f19b70c4-9080-4df4-8196-533541a92eeb", ModuleType.Recording, 1)]
    public partial class POC_job_create_in_QualCheck : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Drop_down_Qualcheck_testRepository repository.
        /// </summary>
        public static Drop_down_Qualcheck_testRepository repo = Drop_down_Qualcheck_testRepository.Instance;

        static POC_job_create_in_QualCheck instance = new POC_job_create_in_QualCheck();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public POC_job_create_in_QualCheck()
        {
            Job_id_clip = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static POC_job_create_in_QualCheck Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable Job_id_clip.
        /// </summary>
        [TestVariable("ec5838d9-1dfb-4aac-9826-7e710d0e6293")]
        public string Job_id_clip
        {
            get { return repo.Job_id_clip; }
            set { repo.Job_id_clip = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Application", "Run application 'C:\\Users\\Sunjeet.Khokhar\\Desktop\\Qualcheck Central QA.nal' with arguments '' in normal mode.", new RecordItemIndex(0));
            Host.Local.RunApplication("C:\\Users\\Sunjeet.Khokhar\\Desktop\\Qualcheck Central QA.nal", "", "C:\\Users\\Sunjeet.Khokhar\\Desktop", false);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck4.Button1012' at 51;10.", repo.Qualcheck4.Button1012Info, new RecordItemIndex(1));
            repo.Qualcheck4.Button1012.Click("51;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck4.Text1011' at 7;11.", repo.Qualcheck4.Text1011Info, new RecordItemIndex(2));
            repo.Qualcheck4.Text1011.Click("7;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'ferkatovo' with focus on 'Qualcheck4.Text1011'.", repo.Qualcheck4.Text1011Info, new RecordItemIndex(3));
            repo.Qualcheck4.Text1011.PressKeys("ferkatovo");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}' with focus on 'Qualcheck4.Text1011'.", repo.Qualcheck4.Text1011Info, new RecordItemIndex(4));
            repo.Qualcheck4.Text1011.PressKeys("{Tab}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck4.Button1009' at 42;9.", repo.Qualcheck4.Button1009Info, new RecordItemIndex(5));
            repo.Qualcheck4.Button1009.Click("42;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck4.Text1010' at 9;12.", repo.Qualcheck4.Text1010Info, new RecordItemIndex(6));
            repo.Qualcheck4.Text1010.Click("9;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'qualcheck' with focus on 'Qualcheck4.Text1010'.", repo.Qualcheck4.Text1010Info, new RecordItemIndex(7));
            repo.Qualcheck4.Text1010.PressKeys("qualcheck");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck4.Button1002' at 24;10.", repo.Qualcheck4.Button1002Info, new RecordItemIndex(8));
            repo.Qualcheck4.Button1002.Click("24;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck5.Entry' at 13;4.", repo.Qualcheck5.EntryInfo, new RecordItemIndex(9));
            repo.Qualcheck5.Entry.Click("13;4");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck2.Jobs' at 37;6.", repo.Qualcheck2.JobsInfo, new RecordItemIndex(10));
            repo.Qualcheck2.Jobs.Click("37;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck5.Button1004' at 85;5.", repo.Qualcheck5.Button1004Info, new RecordItemIndex(11));
            repo.Qualcheck5.Button1004.Click("85;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck4.RadioButton2' at 9;11.", repo.Qualcheck4.RadioButton2Info, new RecordItemIndex(12));
            repo.Qualcheck4.RadioButton2.Click("9;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck4.TextT12' at 150;1.", repo.Qualcheck4.TextT12Info, new RecordItemIndex(13));
            repo.Qualcheck4.TextT12.Click("150;1");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck4.ListItemNZGAPManualNumber' at 223;10.", repo.Qualcheck4.ListItemNZGAPManualNumberInfo, new RecordItemIndex(14));
            repo.Qualcheck4.ListItemNZGAPManualNumber.Click("223;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck3.LineDown' at 5;13.", repo.Qualcheck3.LineDownInfo, new RecordItemIndex(15));
            repo.Qualcheck3.LineDown.Click("5;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck3.LineDown' at 5;13.", repo.Qualcheck3.LineDownInfo, new RecordItemIndex(16));
            repo.Qualcheck3.LineDown.Click("5;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck3.LineDown' at 5;13.", repo.Qualcheck3.LineDownInfo, new RecordItemIndex(17));
            repo.Qualcheck3.LineDown.Click("5;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck3.LineDown' at 5;13.", repo.Qualcheck3.LineDownInfo, new RecordItemIndex(18));
            repo.Qualcheck3.LineDown.Click("5;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck3.LineDown' at 5;13.", repo.Qualcheck3.LineDownInfo, new RecordItemIndex(19));
            repo.Qualcheck3.LineDown.Click("5;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck3.LineDown' at 5;13.", repo.Qualcheck3.LineDownInfo, new RecordItemIndex(20));
            repo.Qualcheck3.LineDown.Click("5;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck3.LineDown' at 5;13.", repo.Qualcheck3.LineDownInfo, new RecordItemIndex(21));
            repo.Qualcheck3.LineDown.Click("5;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck3.LineDown' at 5;13.", repo.Qualcheck3.LineDownInfo, new RecordItemIndex(22));
            repo.Qualcheck3.LineDown.Click("5;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck3.LineDown' at 5;13.", repo.Qualcheck3.LineDownInfo, new RecordItemIndex(23));
            repo.Qualcheck3.LineDown.Click("5;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck3.LineDown' at 5;13.", repo.Qualcheck3.LineDownInfo, new RecordItemIndex(24));
            repo.Qualcheck3.LineDown.Click("5;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck3.LineDown' at 5;13.", repo.Qualcheck3.LineDownInfo, new RecordItemIndex(25));
            repo.Qualcheck3.LineDown.Click("5;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck3.LineDown' at 5;13.", repo.Qualcheck3.LineDownInfo, new RecordItemIndex(26));
            repo.Qualcheck3.LineDown.Click("5;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck3.LineDown' at 5;13.", repo.Qualcheck3.LineDownInfo, new RecordItemIndex(27));
            repo.Qualcheck3.LineDown.Click("5;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck3.LineDown' at 5;13.", repo.Qualcheck3.LineDownInfo, new RecordItemIndex(28));
            repo.Qualcheck3.LineDown.Click("5;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck3' at 139;176.", repo.Qualcheck3.SelfInfo, new RecordItemIndex(29));
            repo.Qualcheck3.Self.Click("139;176");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck4.TextT13' at 61;4.", repo.Qualcheck4.TextT13Info, new RecordItemIndex(30));
            repo.Qualcheck4.TextT13.Click("61;4");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '3'.", new RecordItemIndex(31));
            Keyboard.Press("3");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck4.JobTypeT' at 78;8.", repo.Qualcheck4.JobTypeTInfo, new RecordItemIndex(32));
            repo.Qualcheck4.JobTypeT.Click("78;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck4.JobType' at 226;7.", repo.Qualcheck4.JobTypeInfo, new RecordItemIndex(33));
            repo.Qualcheck4.JobType.Click("226;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck3' at 199;16.", repo.Qualcheck3.SelfInfo, new RecordItemIndex(34));
            repo.Qualcheck3.Self.Click("199;16");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Down}'.", new RecordItemIndex(35));
            Keyboard.Press("{Down}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck4.TextT4' at 86;13.", repo.Qualcheck4.TextT4Info, new RecordItemIndex(36));
            repo.Qualcheck4.TextT4.Click("86;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck4.OfficeId' at 94;9.", repo.Qualcheck4.OfficeIdInfo, new RecordItemIndex(37));
            repo.Qualcheck4.OfficeId.Click("94;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck3' at 94;8.", repo.Qualcheck3.SelfInfo, new RecordItemIndex(38));
            repo.Qualcheck3.Self.Click("94;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck4.ExpiryDateT' at 83;12.", repo.Qualcheck4.ExpiryDateTInfo, new RecordItemIndex(39));
            repo.Qualcheck4.ExpiryDateT.Click("83;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck4.Button' at 9;11.", repo.Qualcheck4.ButtonInfo, new RecordItemIndex(40));
            repo.Qualcheck4.Button.Click("9;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck.Button1001' at 3;11.", repo.Qualcheck.Button1001Info, new RecordItemIndex(41));
            repo.Qualcheck.Button1001.Click("3;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck.Button1001' at 3;11.", repo.Qualcheck.Button1001Info, new RecordItemIndex(42));
            repo.Qualcheck.Button1001.Click("3;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck.Cell36' at 9;11.", repo.Qualcheck.Cell36Info, new RecordItemIndex(43));
            repo.Qualcheck.Cell36.Click("9;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck.Button1000' at 29;7.", repo.Qualcheck.Button1000Info, new RecordItemIndex(44));
            repo.Qualcheck.Button1000.Click("29;7");
            Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck4.Element1001' at 13;68.", repo.Qualcheck4.Element1001Info, new RecordItemIndex(45));
            //repo.Qualcheck4.Element1001.Click("13;68");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck4.ListItem1' at 218;9.", repo.Qualcheck4.ListItem1Info, new RecordItemIndex(46));
            //repo.Qualcheck4.ListItem1.Click("218;9");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck3.LineDown' at 7;4.", repo.Qualcheck3.LineDownInfo, new RecordItemIndex(47));
            //repo.Qualcheck3.LineDown.Click("7;4");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck3' at 68;28.", repo.Qualcheck3.SelfInfo, new RecordItemIndex(48));
            //repo.Qualcheck3.Self.Click("68;28");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck4.AnnualAssessment' at 34;11.", repo.Qualcheck4.AnnualAssessmentInfo, new RecordItemIndex(49));
            //repo.Qualcheck4.AnnualAssessment.Click("34;11");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck3' at 143;5.", repo.Qualcheck3.SelfInfo, new RecordItemIndex(50));
            //repo.Qualcheck3.Self.Click("143;5");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck4.Element1001' at 75;105.", repo.Qualcheck4.Element1001Info, new RecordItemIndex(51));
            //repo.Qualcheck4.Element1001.Click("75;105");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck4.Element1001' at 75;105.", repo.Qualcheck4.Element1001Info, new RecordItemIndex(52));
            //repo.Qualcheck4.Element1001.Click("75;105");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck3.LineDown' at 8;11.", repo.Qualcheck3.LineDownInfo, new RecordItemIndex(53));
            //repo.Qualcheck3.LineDown.Click("8;11");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck3.LineDown' at 8;11.", repo.Qualcheck3.LineDownInfo, new RecordItemIndex(54));
            //repo.Qualcheck3.LineDown.Click("8;11");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck3' at 70;60.", repo.Qualcheck3.SelfInfo, new RecordItemIndex(55));
            //repo.Qualcheck3.Self.Click("70;60");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck4.Element1001' at 347;103.", repo.Qualcheck4.Element1001Info, new RecordItemIndex(56));
            //repo.Qualcheck4.Element1001.Click("347;103");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck3' at 89;10.", repo.Qualcheck3.SelfInfo, new RecordItemIndex(57));
            //repo.Qualcheck3.Self.Click("89;10");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck4.Button1003' at 51;19.", repo.Qualcheck4.Button1003Info, new RecordItemIndex(58));
            //repo.Qualcheck4.Button1003.Click("51;19");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck6.TitleBar' at 230;10.", repo.Qualcheck6.TitleBarInfo, new RecordItemIndex(59));
            //repo.Qualcheck6.TitleBar.Click("230;10");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck6.Button2' at 36;14.", repo.Qualcheck6.Button2Info, new RecordItemIndex(60));
            //repo.Qualcheck6.Button2.Click("36;14");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck6' at 333;56.", repo.Qualcheck6.SelfInfo, new RecordItemIndex(61));
            //repo.Qualcheck6.Self.Click("333;56");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck6.Button7' at 35;8.", repo.Qualcheck6.Button7Info, new RecordItemIndex(62));
            //repo.Qualcheck6.Button7.Click("35;8");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck5.Form200.JobIdT' at 67;9.", repo.Qualcheck5.Form200.JobIdTInfo, new RecordItemIndex(63));
            //repo.Qualcheck5.Form200.JobIdT.Click("67;9");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'Qualcheck5.Form200.Text' at 65;2.", repo.Qualcheck5.Form200.TextInfo, new RecordItemIndex(64));
            //repo.Qualcheck5.Form200.Text.MoveTo("65;2");
            //Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'Qualcheck5.Form200.Text' at 73;-6.", repo.Qualcheck5.Form200.TextInfo, new RecordItemIndex(65));
            //repo.Qualcheck5.Form200.Text.MoveTo("73;-6");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'Qualcheck5.Form200.Element1005' at 193;7.", repo.Qualcheck5.Form200.Element1005Info, new RecordItemIndex(66));
            //repo.Qualcheck5.Form200.Element1005.MoveTo("193;7");
            //Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'Qualcheck5.Form200.Text' at 92;9.", repo.Qualcheck5.Form200.TextInfo, new RecordItemIndex(67));
            //repo.Qualcheck5.Form200.Text.Click(System.Windows.Forms.MouseButtons.Right, "92;9");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'SelectionText' from item 'Qualcheck5.Form200.Text' and assigning its value to variable 'Job_id_clip'.", repo.Qualcheck5.Form200.TextInfo, new RecordItemIndex(68));
            //Job_id_clip = repo.Qualcheck5.Form200.Text.Element.GetAttributeValueText("SelectionText");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck2.Copy' at 40;14.", repo.Qualcheck2.CopyInfo, new RecordItemIndex(69));
            //repo.Qualcheck2.Copy.Click("40;14");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck5.Close' at 17;6.", repo.Qualcheck5.CloseInfo, new RecordItemIndex(70));
            //repo.Qualcheck5.Close.Click("17;6");
            //Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck4.Element1001' at 14;63.", repo.Qualcheck4.Element1001Info, new RecordItemIndex(71));
            repo.Qualcheck4.Element1001.Click("14;63");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck4.Element1001' at 205;105.", repo.Qualcheck4.Element1001Info, new RecordItemIndex(72));
            repo.Qualcheck4.Element1001.Click("205;105");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck3.LineDown' at 6;10.", repo.Qualcheck3.LineDownInfo, new RecordItemIndex(73));
            repo.Qualcheck3.LineDown.Click("6;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck3' at 80;29.", repo.Qualcheck3.SelfInfo, new RecordItemIndex(74));
            repo.Qualcheck3.Self.Click("80;29");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck4.Element1001' at 380;103.", repo.Qualcheck4.Element1001Info, new RecordItemIndex(75));
            repo.Qualcheck4.Element1001.Click("380;103");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck3' at 117;7.", repo.Qualcheck3.SelfInfo, new RecordItemIndex(76));
            repo.Qualcheck3.Self.Click("117;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck4.Button1003' at 50;10.", repo.Qualcheck4.Button1003Info, new RecordItemIndex(77));
            repo.Qualcheck4.Button1003.Click("50;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck6.Button2' at 28;12.", repo.Qualcheck6.Button2Info, new RecordItemIndex(78));
            repo.Qualcheck6.Button2.Click("28;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck6.Button7' at 37;10.", repo.Qualcheck6.Button7Info, new RecordItemIndex(79));
            repo.Qualcheck6.Button7.Click("37;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck5.TitleBar' at 1314;14.", repo.Qualcheck5.TitleBarInfo, new RecordItemIndex(80));
            repo.Qualcheck5.TitleBar.Click("1314;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck5.Close' at 23;7.", repo.Qualcheck5.CloseInfo, new RecordItemIndex(81));
            repo.Qualcheck5.Close.Click("23;7");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
