///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;

namespace Drop_down_Qualcheck_test
{
    public partial class POC_job_create_in_QualCheck
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void Mouse_Click_Text()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'Qualcheck5.Form200.Text' at 99;9.", repo.Qualcheck5.Form200.TextInfo);
            repo.Qualcheck5.Form200.Text.Click(System.Windows.Forms.MouseButtons.Right, "99;9");
        }

        public void Mouse_Click_Copy()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Qualcheck2.Copy' at 34;11.", repo.Qualcheck2.CopyInfo);
            repo.Qualcheck2.Copy.Click("34;11");
        }

        public void get_clip_text()
        {
        	string clipboardtext = System.Windows.Forms.Clipboard.GetText(); 
        }

    }
}