///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CRM
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The account_details_edit_is_read_only recording.
    /// </summary>
    [TestModule("95b316f9-316d-42a6-beba-5e6ea7483d57", ModuleType.Recording, 1)]
    public partial class account_details_edit_is_read_only : ITestModule
    {
        /// <summary>
        /// Holds an instance of the CRMRepository repository.
        /// </summary>
        public static CRMRepository repo = CRMRepository.Instance;

        static account_details_edit_is_read_only instance = new account_details_edit_is_read_only();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public account_details_edit_is_read_only()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static account_details_edit_is_read_only Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            // Pre-req : 1. No appropriate AD CRM login to be active in the browser 2. No browser window should be open before running the tests
            //Report.Log(ReportLevel.Info, "Website", "Pre-req : 1. No appropriate AD CRM login to be active in the browser 2. No browser window should be open before running the tests\r\nOpening web site 'https://asurequalitytest.crm6.dynamics.com/main.aspx' with browser 'chrome' in normal mode.", new RecordItemIndex(0));
            //Host.Local.OpenBrowser("https://asurequalitytest.crm6.dynamics.com/main.aspx", "chrome", "", false, false, false, false, false);
            //Delay.Milliseconds(0);
            
            // This test logs into CRM and open up an account's details and validates that the details are read only
            Report.Log(ReportLevel.Info, "Mouse", "This test logs into CRM and open up an account's details and validates that the details are read only\r\nMouse Left Click item 'DashboardsAQCustomerServicesDashboa.HomeButtonImageNavTabButtonImageSandbox' at 10;10.", repo.DashboardsAQCustomerServicesDashboa.HomeButtonImageNavTabButtonImageSandboxInfo, new RecordItemIndex(1));
            repo.DashboardsAQCustomerServicesDashboa.HomeButtonImageNavTabButtonImageSandbox.Click("10;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.NavActionButtonIcon' at 39;33.", repo.DashboardsAQCustomerServicesDashboa.NavActionButtonIconInfo, new RecordItemIndex(2));
            repo.DashboardsAQCustomerServicesDashboa.NavActionButtonIcon.Click("39;33");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.Accounts' at 14;6.", repo.DashboardsAQCustomerServicesDashboa.AccountsInfo, new RecordItemIndex(3));
            repo.DashboardsAQCustomerServicesDashboa.Accounts.Click("14;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.ContentIFrame0.CrmGridFindCriteria' at 37;13.", repo.DashboardsAQCustomerServicesDashboa.ContentIFrame0.CrmGridFindCriteriaInfo, new RecordItemIndex(4));
            repo.DashboardsAQCustomerServicesDashboa.ContentIFrame0.CrmGridFindCriteria.Click("37;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LShiftKey down}F{LShiftKey up}onterra{Space}australia' with focus on 'DashboardsAQCustomerServicesDashboa.ContentIFrame0.CrmGridFindCriteria'.", repo.DashboardsAQCustomerServicesDashboa.ContentIFrame0.CrmGridFindCriteriaInfo, new RecordItemIndex(5));
            repo.DashboardsAQCustomerServicesDashboa.ContentIFrame0.CrmGridFindCriteria.PressKeys("{LShiftKey down}F{LShiftKey up}onterra{Space}australia");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}' with focus on 'DashboardsAQCustomerServicesDashboa.ContentIFrame0.CrmGridFindCriteria'.", repo.DashboardsAQCustomerServicesDashboa.ContentIFrame0.CrmGridFindCriteriaInfo, new RecordItemIndex(6));
            repo.DashboardsAQCustomerServicesDashboa.ContentIFrame0.CrmGridFindCriteria.PressKeys("{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.ContentIFrame0.FonterraAustraliaPtyLtd' at 9;8.", repo.DashboardsAQCustomerServicesDashboa.ContentIFrame0.FonterraAustraliaPtyLtdInfo, new RecordItemIndex(7));
            repo.DashboardsAQCustomerServicesDashboa.ContentIFrame0.FonterraAustraliaPtyLtd.Click("9;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'DashboardsAQCustomerServicesDashboa.ContentIFrame1.TdAreas' at 1565;70.", repo.DashboardsAQCustomerServicesDashboa.ContentIFrame1.TdAreasInfo, new RecordItemIndex(8));
            repo.DashboardsAQCustomerServicesDashboa.ContentIFrame1.TdAreas.MoveTo("1565;70");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'DashboardsAQCustomerServicesDashboa.ContentIFrame1.TdAreas' at 1573;62.", repo.DashboardsAQCustomerServicesDashboa.ContentIFrame1.TdAreasInfo, new RecordItemIndex(9));
            repo.DashboardsAQCustomerServicesDashboa.ContentIFrame1.TdAreas.MoveTo("1573;62");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'DashboardsAQCustomerServicesDashboa.ContentIFrame1.RofContainer' at 1599;655.", repo.DashboardsAQCustomerServicesDashboa.ContentIFrame1.RofContainerInfo, new RecordItemIndex(10));
            repo.DashboardsAQCustomerServicesDashboa.ContentIFrame1.RofContainer.MoveTo("1599;655");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            // The validation for read only
            Report.Log(ReportLevel.Info, "Validation", "The validation for read only\r\nValidating AttributeEqual (InnerText='Read only') on item 'DashboardsAQCustomerServicesDashboa.ContentIFrame1.TitlefooterStatuscontrol'.", repo.DashboardsAQCustomerServicesDashboa.ContentIFrame1.TitlefooterStatuscontrolInfo, new RecordItemIndex(11));
            Validate.Attribute(repo.DashboardsAQCustomerServicesDashboa.ContentIFrame1.TitlefooterStatuscontrolInfo, "InnerText", "Read only");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.ContentIFrame1.TitlefooterStatuscontrol' at 39;6.", repo.DashboardsAQCustomerServicesDashboa.ContentIFrame1.TitlefooterStatuscontrolInfo, new RecordItemIndex(12));
            repo.DashboardsAQCustomerServicesDashboa.ContentIFrame1.TitlefooterStatuscontrol.Click("39;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.NavTabButtonImageContainer1' at 6;32.", repo.DashboardsAQCustomerServicesDashboa.NavTabButtonImageContainer1Info, new RecordItemIndex(13));
            repo.DashboardsAQCustomerServicesDashboa.NavTabButtonImageContainer1.Click("6;32");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.Sales' at 13;45.", repo.DashboardsAQCustomerServicesDashboa.SalesInfo, new RecordItemIndex(14));
            repo.DashboardsAQCustomerServicesDashboa.Sales.Click("13;45");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.Accounts' at 29;11.", repo.DashboardsAQCustomerServicesDashboa.AccountsInfo, new RecordItemIndex(15));
            repo.DashboardsAQCustomerServicesDashboa.Accounts.Click("29;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.ContentIFrame0.CrmGridClearCriteriaImg' at 6;9.", repo.DashboardsAQCustomerServicesDashboa.ContentIFrame0.CrmGridClearCriteriaImgInfo, new RecordItemIndex(16));
            repo.DashboardsAQCustomerServicesDashboa.ContentIFrame0.CrmGridClearCriteriaImg.Click("6;9");
            Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AccountsAllAccountsMicrosoftDynami.Client' at 1567;3.", repo.AccountsAllAccountsMicrosoftDynami.ClientInfo, new RecordItemIndex(17));
            //repo.AccountsAllAccountsMicrosoftDynami.Client.Click("1567;3");
            //Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
