///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CRM
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Add_a_task recording.
    /// </summary>
    [TestModule("260ffd1b-0c8f-4b05-ae72-5014bf728d4f", ModuleType.Recording, 1)]
    public partial class Add_a_task : ITestModule
    {
        /// <summary>
        /// Holds an instance of the CRMRepository repository.
        /// </summary>
        public static CRMRepository repo = CRMRepository.Instance;

        static Add_a_task instance = new Add_a_task();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Add_a_task()
        {
            Account_to_search = "fonterra";
            month_text = "october2016";
            get_task_name = "";
            validate_txt = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Add_a_task Instance
        {
            get { return instance; }
        }

#region Variables

        string _Account_to_search;

        /// <summary>
        /// Gets or sets the value of variable Account_to_search.
        /// </summary>
        [TestVariable("408d21e0-2a67-4865-9f03-89cde2a8c21a")]
        public string Account_to_search
        {
            get { return _Account_to_search; }
            set { _Account_to_search = value; }
        }

        string _get_task_name;

        /// <summary>
        /// Gets or sets the value of variable get_task_name.
        /// </summary>
        [TestVariable("4aaf35ca-b946-4126-870f-a6499bddbcc3")]
        public string get_task_name
        {
            get { return _get_task_name; }
            set { _get_task_name = value; }
        }

        string _validate_txt;

        /// <summary>
        /// Gets or sets the value of variable validate_txt.
        /// </summary>
        [TestVariable("8adeb8db-ec69-4a43-9d50-7d91e7310590")]
        public string validate_txt
        {
            get { return _validate_txt; }
            set { _validate_txt = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable month_text.
        /// </summary>
        [TestVariable("2677a97f-061b-4ef3-9dd3-85200f2c0ac2")]
        public string month_text
        {
            get { return repo.month_text; }
            set { repo.month_text = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'https://asurequalitytest.crm6.dynamics.com/main.aspx' with browser 'chrome' in normal mode.", new RecordItemIndex(0));
            Host.Local.OpenBrowser("https://asurequalitytest.crm6.dynamics.com/main.aspx", "chrome", "", false, false, false, false, false);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.NavTabButtonImageContainer' at 8;37.", repo.DashboardsAQCustomerServicesDashboa.NavTabButtonImageContainerInfo, new RecordItemIndex(1));
            repo.DashboardsAQCustomerServicesDashboa.NavTabButtonImageContainer.Click("8;37");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.Accounts' at 14;14.", repo.DashboardsAQCustomerServicesDashboa.AccountsInfo, new RecordItemIndex(2));
            repo.DashboardsAQCustomerServicesDashboa.Accounts.Click("14;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.ContentIFrame0.CrmGridFindCriteria' at 11;7.", repo.DashboardsAQCustomerServicesDashboa.ContentIFrame0.CrmGridFindCriteriaInfo, new RecordItemIndex(3));
            repo.DashboardsAQCustomerServicesDashboa.ContentIFrame0.CrmGridFindCriteria.Click("11;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'fonterra' with focus on 'DashboardsAQCustomerServicesDashboa.ContentIFrame0.CrmGridFindCriteria'.", repo.DashboardsAQCustomerServicesDashboa.ContentIFrame0.CrmGridFindCriteriaInfo, new RecordItemIndex(4));
            repo.DashboardsAQCustomerServicesDashboa.ContentIFrame0.CrmGridFindCriteria.PressKeys("fonterra");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.ContentIFrame0.CrmGridFindCriteriaImg' at 7;9.", repo.DashboardsAQCustomerServicesDashboa.ContentIFrame0.CrmGridFindCriteriaImgInfo, new RecordItemIndex(5));
            repo.DashboardsAQCustomerServicesDashboa.ContentIFrame0.CrmGridFindCriteriaImg.Click("7;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'DashboardsAQCustomerServicesDashboa.ContentIFrame0.CrmGridDivDataArea' at 1526;182.", repo.DashboardsAQCustomerServicesDashboa.ContentIFrame0.CrmGridDivDataAreaInfo, new RecordItemIndex(6));
            repo.DashboardsAQCustomerServicesDashboa.ContentIFrame0.CrmGridDivDataArea.MoveTo("1526;182");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'DashboardsAQCustomerServicesDashboa.ContentIFrame0.CrmGridDivDataArea' at 1534;174.", repo.DashboardsAQCustomerServicesDashboa.ContentIFrame0.CrmGridDivDataAreaInfo, new RecordItemIndex(7));
            repo.DashboardsAQCustomerServicesDashboa.ContentIFrame0.CrmGridDivDataArea.MoveTo("1534;174");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'DashboardsAQCustomerServicesDashboa.ContentIFrame0.SomeTdTag1' at 2;480.", repo.DashboardsAQCustomerServicesDashboa.ContentIFrame0.SomeTdTag1Info, new RecordItemIndex(8));
            repo.DashboardsAQCustomerServicesDashboa.ContentIFrame0.SomeTdTag1.MoveTo("2;480");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.ContentIFrame0.FonterraAustraliaPtyLtd' at 77;3.", repo.DashboardsAQCustomerServicesDashboa.ContentIFrame0.FonterraAustraliaPtyLtdInfo, new RecordItemIndex(9));
            repo.DashboardsAQCustomerServicesDashboa.ContentIFrame0.FonterraAustraliaPtyLtd.Click("77;3");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.ContentIFrame1.ActivityLabelinlineactivitybar4212' at 14;4.", repo.DashboardsAQCustomerServicesDashboa.ContentIFrame1.ActivityLabelinlineactivitybar4212Info, new RecordItemIndex(10));
            repo.DashboardsAQCustomerServicesDashboa.ContentIFrame1.ActivityLabelinlineactivitybar4212.Click("14;4");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.ContentIFrame1.QuickCreateActivity4212controlIdSubject' at 24;13.", repo.DashboardsAQCustomerServicesDashboa.ContentIFrame1.QuickCreateActivity4212controlIdSubjectInfo, new RecordItemIndex(11));
            repo.DashboardsAQCustomerServicesDashboa.ContentIFrame1.QuickCreateActivity4212controlIdSubject.Click("24;13");
            Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LShiftKey down}t{LShiftKey up}' with focus on 'DashboardsAQCustomerServicesDashboa.ContentIFrame1.QuickCreateActivity4212controlIdSubject'.", repo.DashboardsAQCustomerServicesDashboa.ContentIFrame1.QuickCreateActivity4212controlIdSubjectInfo, new RecordItemIndex(12));
            //repo.DashboardsAQCustomerServicesDashboa.ContentIFrame1.QuickCreateActivity4212controlIdSubject.PressKeys("{LShiftKey down}t{LShiftKey up}");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '7' with focus on 'DashboardsAQCustomerServicesDashboa.ContentIFrame1.QuickCreateActivity4212controlIdSubject'.", repo.DashboardsAQCustomerServicesDashboa.ContentIFrame1.QuickCreateActivity4212controlIdSubjectInfo, new RecordItemIndex(13));
            //repo.DashboardsAQCustomerServicesDashboa.ContentIFrame1.QuickCreateActivity4212controlIdSubject.PressKeys("7");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 't7october2016' with focus on 'DashboardsAQCustomerServicesDashboa.ContentIFrame1.QuickCreateActivity4212controlIdSubject'.", repo.DashboardsAQCustomerServicesDashboa.ContentIFrame1.QuickCreateActivity4212controlIdSubjectInfo, new RecordItemIndex(14));
            //repo.DashboardsAQCustomerServicesDashboa.ContentIFrame1.QuickCreateActivity4212controlIdSubject.PressKeys("t7october2016");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$month_text' with focus on 'DashboardsAQCustomerServicesDashboa.ContentIFrame1.QuickCreateActivity4212controlIdSubject'.", repo.DashboardsAQCustomerServicesDashboa.ContentIFrame1.QuickCreateActivity4212controlIdSubjectInfo, new RecordItemIndex(15));
            repo.DashboardsAQCustomerServicesDashboa.ContentIFrame1.QuickCreateActivity4212controlIdSubject.PressKeys(month_text);
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'october2016' with focus on 'DashboardsAQCustomerServicesDashboa.ContentIFrame1.QuickCreateActivity4212controlIdSubject'.", repo.DashboardsAQCustomerServicesDashboa.ContentIFrame1.QuickCreateActivity4212controlIdSubjectInfo, new RecordItemIndex(16));
            //repo.DashboardsAQCustomerServicesDashboa.ContentIFrame1.QuickCreateActivity4212controlIdSubject.PressKeys("october2016");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'DashboardsAQCustomerServicesDashboa.ContentIFrame1.ContentNotescontrol' at 591;111.", repo.DashboardsAQCustomerServicesDashboa.ContentIFrame1.ContentNotescontrolInfo, new RecordItemIndex(17));
            repo.DashboardsAQCustomerServicesDashboa.ContentIFrame1.ContentNotescontrol.MoveTo("591;111");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'DashboardsAQCustomerServicesDashboa.ContentIFrame1.ContentNotescontrol' at 599;103.", repo.DashboardsAQCustomerServicesDashboa.ContentIFrame1.ContentNotescontrolInfo, new RecordItemIndex(18));
            repo.DashboardsAQCustomerServicesDashboa.ContentIFrame1.ContentNotescontrol.MoveTo("599;103");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'DashboardsAQCustomerServicesDashboa.ContentIFrame1.TableTag7a073b7c542224183d26B2a7eb2' at 626;401.", repo.DashboardsAQCustomerServicesDashboa.ContentIFrame1.TableTag7a073b7c542224183d26B2a7eb2Info, new RecordItemIndex(19));
            repo.DashboardsAQCustomerServicesDashboa.ContentIFrame1.TableTag7a073b7c542224183d26B2a7eb2.MoveTo("626;401");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.ContentIFrame1.Save4212QuickCreateButton' at 19;6.", repo.DashboardsAQCustomerServicesDashboa.ContentIFrame1.Save4212QuickCreateButtonInfo, new RecordItemIndex(20));
            repo.DashboardsAQCustomerServicesDashboa.ContentIFrame1.Save4212QuickCreateButton.Click("19;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.ContentIFrame1.FonterraAustraliaPtyLtd' at 167;19.", repo.DashboardsAQCustomerServicesDashboa.ContentIFrame1.FonterraAustraliaPtyLtdInfo, new RecordItemIndex(21));
            repo.DashboardsAQCustomerServicesDashboa.ContentIFrame1.FonterraAustraliaPtyLtd.Click("167;19");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.MicrosoftDynamicsCRMMicrosoftDynami' at 130;30.", repo.DashboardsAQCustomerServicesDashboa.MicrosoftDynamicsCRMMicrosoftDynamiInfo, new RecordItemIndex(22));
            repo.DashboardsAQCustomerServicesDashboa.MicrosoftDynamicsCRMMicrosoftDynami.Click("130;30");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.DashboardFrame.Component90b0b4aFindCriteria' at 143;9.", repo.DashboardsAQCustomerServicesDashboa.DashboardFrame.Component90b0b4aFindCriteriaInfo, new RecordItemIndex(23));
            repo.DashboardsAQCustomerServicesDashboa.DashboardFrame.Component90b0b4aFindCriteria.Click("143;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$month_text' with focus on 'DashboardsAQCustomerServicesDashboa.DashboardFrame.Component90b0b4aFindCriteria'.", repo.DashboardsAQCustomerServicesDashboa.DashboardFrame.Component90b0b4aFindCriteriaInfo, new RecordItemIndex(24));
            repo.DashboardsAQCustomerServicesDashboa.DashboardFrame.Component90b0b4aFindCriteria.PressKeys(month_text);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.DashboardFrame.Component90b0b4aFindCriteriaImg' at 11;8.", repo.DashboardsAQCustomerServicesDashboa.DashboardFrame.Component90b0b4aFindCriteriaImgInfo, new RecordItemIndex(25));
            repo.DashboardsAQCustomerServicesDashboa.DashboardFrame.Component90b0b4aFindCriteriaImg.Click("11;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.DashboardFrame.Nobr1' at 143;15.", repo.DashboardsAQCustomerServicesDashboa.DashboardFrame.Nobr1Info, new RecordItemIndex(26));
            repo.DashboardsAQCustomerServicesDashboa.DashboardFrame.Nobr1.Click("143;15");
            Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Set Value", "Setting attribute title to 'foobar' on item 'DashboardsAQCustomerServicesDashboa.DashboardFrame.Nobr1'.", repo.DashboardsAQCustomerServicesDashboa.DashboardFrame.Nobr1Info, new RecordItemIndex(27));
            //repo.DashboardsAQCustomerServicesDashboa.DashboardFrame.Nobr1.Element.SetAttributeValue("title", "foobar");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (title=$month_text) on item 'DashboardsAQCustomerServicesDashboa.DashboardFrame.Nobr1'.", repo.DashboardsAQCustomerServicesDashboa.DashboardFrame.Nobr1Info, new RecordItemIndex(28));
            Validate.Attribute(repo.DashboardsAQCustomerServicesDashboa.DashboardFrame.Nobr1Info, "title", month_text);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.DashboardFrame.HttpsAsurequalitytestCrm6DynamicsC' at 6;8.", repo.DashboardsAQCustomerServicesDashboa.DashboardFrame.HttpsAsurequalitytestCrm6DynamicsCInfo, new RecordItemIndex(29));
            repo.DashboardsAQCustomerServicesDashboa.DashboardFrame.HttpsAsurequalitytestCrm6DynamicsC.Click("6;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.DvFooter' at 262;7.", repo.DashboardsAQCustomerServicesDashboa.DvFooterInfo, new RecordItemIndex(30));
            repo.DashboardsAQCustomerServicesDashboa.DvFooter.Click("262;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.DivTagDelete' at 20;7.", repo.DashboardsAQCustomerServicesDashboa.DivTagDeleteInfo, new RecordItemIndex(31));
            repo.DashboardsAQCustomerServicesDashboa.DivTagDelete.Click("20;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.NavTabButtonImageContainer' at 8;38.", repo.DashboardsAQCustomerServicesDashboa.NavTabButtonImageContainerInfo, new RecordItemIndex(32));
            repo.DashboardsAQCustomerServicesDashboa.NavTabButtonImageContainer.Click("8;38");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.Accounts' at 9;18.", repo.DashboardsAQCustomerServicesDashboa.AccountsInfo, new RecordItemIndex(33));
            repo.DashboardsAQCustomerServicesDashboa.Accounts.Click("9;18");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.ContentIFrame0.CrmGridFindCriteria' at 67;7.", repo.DashboardsAQCustomerServicesDashboa.ContentIFrame0.CrmGridFindCriteriaInfo, new RecordItemIndex(34));
            repo.DashboardsAQCustomerServicesDashboa.ContentIFrame0.CrmGridFindCriteria.Click("67;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.ContentIFrame0.CrmGridClearCriteriaImg' at 10;6.", repo.DashboardsAQCustomerServicesDashboa.ContentIFrame0.CrmGridClearCriteriaImgInfo, new RecordItemIndex(35));
            repo.DashboardsAQCustomerServicesDashboa.ContentIFrame0.CrmGridClearCriteriaImg.Click("10;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.MicrosoftDynamicsCRMMicrosoftDynami' at 192;21.", repo.DashboardsAQCustomerServicesDashboa.MicrosoftDynamicsCRMMicrosoftDynamiInfo, new RecordItemIndex(36));
            repo.DashboardsAQCustomerServicesDashboa.MicrosoftDynamicsCRMMicrosoftDynami.Click("192;21");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa1.Close' at 6;18.", repo.DashboardsAQCustomerServicesDashboa1.CloseInfo, new RecordItemIndex(37));
            repo.DashboardsAQCustomerServicesDashboa1.Close.Click("6;18");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
