///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CRM
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Adding_a_case recording.
    /// </summary>
    [TestModule("a1cfd953-0bdc-4ad8-9417-f3734b6ed904", ModuleType.Recording, 1)]
    public partial class Adding_a_case : ITestModule
    {
        /// <summary>
        /// Holds an instance of the CRMRepository repository.
        /// </summary>
        public static CRMRepository repo = CRMRepository.Instance;

        static Adding_a_case instance = new Adding_a_case();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Adding_a_case()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Adding_a_case Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'https://asurequalitytest.crm6.dynamics.com/main.aspx' with browser 'chrome' in normal mode.", new RecordItemIndex(0));
            Host.Local.OpenBrowser("https://asurequalitytest.crm6.dynamics.com/main.aspx", "chrome", "", false, false, false, false, false);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.NavTabGlobalCreateImage' at 10;14.", repo.DashboardsAQCustomerServicesDashboa.NavTabGlobalCreateImageInfo, new RecordItemIndex(1));
            repo.DashboardsAQCustomerServicesDashboa.NavTabGlobalCreateImage.Click("10;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.Case' at 3;4.", repo.DashboardsAQCustomerServicesDashboa.CaseInfo, new RecordItemIndex(2));
            repo.DashboardsAQCustomerServicesDashboa.Case.Click("3;4");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.NavBarGloablQuickCreate.OptionTag2' at 54;8.", repo.DashboardsAQCustomerServicesDashboa.NavBarGloablQuickCreate.OptionTag2Info, new RecordItemIndex(3));
            repo.DashboardsAQCustomerServicesDashboa.NavBarGloablQuickCreate.OptionTag2.Click("54;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.NavBarGloablQuickCreate.MsCrmInlineValueMsCrmInlineEditH' at 40;9.", repo.DashboardsAQCustomerServicesDashboa.NavBarGloablQuickCreate.MsCrmInlineValueMsCrmInlineEditHInfo, new RecordItemIndex(4));
            repo.DashboardsAQCustomerServicesDashboa.NavBarGloablQuickCreate.MsCrmInlineValueMsCrmInlineEditH.Click("40;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LShiftKey down}T{LShiftKey up}est{Space}case{Space}'.", new RecordItemIndex(5));
            Keyboard.Press("{LShiftKey down}T{LShiftKey up}est{Space}case{Space}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'for{Space}{LShiftKey down}F{LShiftKey up}onterra{Space}123'.", new RecordItemIndex(6));
            Keyboard.Press("for{Space}{LShiftKey down}F{LShiftKey up}onterra{Space}123");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.NavBarGloablQuickCreate.MsCrmInlineValueMsCrmInlineLookup' at 30;7.", repo.DashboardsAQCustomerServicesDashboa.NavBarGloablQuickCreate.MsCrmInlineValueMsCrmInlineLookupInfo, new RecordItemIndex(7));
            repo.DashboardsAQCustomerServicesDashboa.NavBarGloablQuickCreate.MsCrmInlineValueMsCrmInlineLookup.Click("30;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LShiftKey down}F{LShiftKey up}onterra{Space}australia{Return}'.", new RecordItemIndex(8));
            Keyboard.Press("{LShiftKey down}F{LShiftKey up}onterra{Space}australia{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'DashboardsAQCustomerServicesDashboa.NavBarGloablQuickCreate.MsCrmILMenu' at 323;102.", repo.DashboardsAQCustomerServicesDashboa.NavBarGloablQuickCreate.MsCrmILMenuInfo, new RecordItemIndex(9));
            repo.DashboardsAQCustomerServicesDashboa.NavBarGloablQuickCreate.MsCrmILMenu.MoveTo("323;102");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'DashboardsAQCustomerServicesDashboa.NavBarGloablQuickCreate.MsCrmILMenu' at 320;190.", repo.DashboardsAQCustomerServicesDashboa.NavBarGloablQuickCreate.MsCrmILMenuInfo, new RecordItemIndex(10));
            repo.DashboardsAQCustomerServicesDashboa.NavBarGloablQuickCreate.MsCrmILMenu.MoveTo("320;190");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.NavBarGloablQuickCreate.FonterraAustraliaPtyLtd' at 84;10.", repo.DashboardsAQCustomerServicesDashboa.NavBarGloablQuickCreate.FonterraAustraliaPtyLtdInfo, new RecordItemIndex(11));
            repo.DashboardsAQCustomerServicesDashboa.NavBarGloablQuickCreate.FonterraAustraliaPtyLtd.Click("84;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.GlobalquickcreateSaveButtonNavBarGloa' at 23;9.", repo.DashboardsAQCustomerServicesDashboa.GlobalquickcreateSaveButtonNavBarGloaInfo, new RecordItemIndex(12));
            repo.DashboardsAQCustomerServicesDashboa.GlobalquickcreateSaveButtonNavBarGloa.Click("23;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.CaseTestCaseForFonterra123WasCrea' at 60;5.", repo.DashboardsAQCustomerServicesDashboa.CaseTestCaseForFonterra123WasCreaInfo, new RecordItemIndex(13));
            repo.DashboardsAQCustomerServicesDashboa.CaseTestCaseForFonterra123WasCrea.Click("60;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'DashboardsAQCustomerServicesDashboa.CaseTestCaseForFonterra123WasCrea'.", repo.DashboardsAQCustomerServicesDashboa.CaseTestCaseForFonterra123WasCreaInfo, new RecordItemIndex(14));
            Validate.Exists(repo.DashboardsAQCustomerServicesDashboa.CaseTestCaseForFonterra123WasCreaInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CaseTestCaseForFonterra123Googl.Close' at 12;14.", repo.CaseTestCaseForFonterra123Googl.CloseInfo, new RecordItemIndex(15));
            repo.CaseTestCaseForFonterra123Googl.Close.Click("12;14");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
