///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CRM
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Can_not_create_delete_account recording.
    /// </summary>
    [TestModule("417cdab7-85de-4c75-8653-6571458e69bd", ModuleType.Recording, 1)]
    public partial class Can_not_create_delete_account : ITestModule
    {
        /// <summary>
        /// Holds an instance of the CRMRepository repository.
        /// </summary>
        public static CRMRepository repo = CRMRepository.Instance;

        static Can_not_create_delete_account instance = new Can_not_create_delete_account();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Can_not_create_delete_account()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Can_not_create_delete_account Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            // Pre-req : 1. No appropriate AD CRM login to be active in the browser 2. No browser window should be open before running the tests
            //Report.Log(ReportLevel.Info, "Website", "Pre-req : 1. No appropriate AD CRM login to be active in the browser 2. No browser window should be open before running the tests\r\nOpening web site 'https://asurequalitytest.crm6.dynamics.com/main.aspx' with browser 'chrome' in normal mode.", new RecordItemIndex(0));
            //Host.Local.OpenBrowser("https://asurequalitytest.crm6.dynamics.com/main.aspx", "chrome", "", false, false, false, false, false);
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.HomeButtonImageNavTabButtonImageSandbox' at 16;11.", repo.DashboardsAQCustomerServicesDashboa.HomeButtonImageNavTabButtonImageSandboxInfo, new RecordItemIndex(1));
            repo.DashboardsAQCustomerServicesDashboa.HomeButtonImageNavTabButtonImageSandbox.Click("16;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.NavActionButtonIcon' at 83;26.", repo.DashboardsAQCustomerServicesDashboa.NavActionButtonIconInfo, new RecordItemIndex(2));
            repo.DashboardsAQCustomerServicesDashboa.NavActionButtonIcon.Click("83;26");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.Accounts' at 8;5.", repo.DashboardsAQCustomerServicesDashboa.AccountsInfo, new RecordItemIndex(3));
            repo.DashboardsAQCustomerServicesDashboa.Accounts.Click("8;5");
            Delay.Milliseconds(200);
            
            // Validate that the "NEW" button does not exist on the Accounts page
            Report.Log(ReportLevel.Info, "Validation", "Validate that the \"NEW\" button does not exist on the Accounts page\r\nValidating NotExists on item 'DashboardsAQCustomerServicesDashboa.MsCrmMenuLabel'.", repo.DashboardsAQCustomerServicesDashboa.MsCrmMenuLabelInfo, new RecordItemIndex(4));
            Validate.NotExists(repo.DashboardsAQCustomerServicesDashboa.MsCrmMenuLabelInfo);
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.MsCrmMenuLabel' at 37;7.", repo.DashboardsAQCustomerServicesDashboa.MsCrmMenuLabelInfo, new RecordItemIndex(5));
            //repo.DashboardsAQCustomerServicesDashboa.MsCrmMenuLabel.Click("37;7");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.SpanTagDelete' at 16;0.", repo.DashboardsAQCustomerServicesDashboa.SpanTagDeleteInfo, new RecordItemIndex(6));
            //repo.DashboardsAQCustomerServicesDashboa.SpanTagDelete.Click("16;0");
            //Delay.Milliseconds(200);
            
            // Validate that the "DELETE" button does not exist on the accounts page
            Report.Log(ReportLevel.Info, "Validation", "Validate that the \"DELETE\" button does not exist on the accounts page\r\nValidating NotExists on item 'DashboardsAQCustomerServicesDashboa.SpanTagDelete'.", repo.DashboardsAQCustomerServicesDashboa.SpanTagDeleteInfo, new RecordItemIndex(7));
            Validate.NotExists(repo.DashboardsAQCustomerServicesDashboa.SpanTagDeleteInfo);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
