///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CRM
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Can_not_edit_biling_and_acc_number recording.
    /// </summary>
    [TestModule("3f6da40b-b87b-433e-9fd7-56ae750ea1e8", ModuleType.Recording, 1)]
    public partial class Can_not_edit_biling_and_acc_number : ITestModule
    {
        /// <summary>
        /// Holds an instance of the CRMRepository repository.
        /// </summary>
        public static CRMRepository repo = CRMRepository.Instance;

        static Can_not_edit_biling_and_acc_number instance = new Can_not_edit_biling_and_acc_number();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Can_not_edit_biling_and_acc_number()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Can_not_edit_biling_and_acc_number Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            //Report.Log(ReportLevel.Info, "Website", "Opening web site 'https://asurequalitytest.crm6.dynamics.com/main.aspx' with browser 'chrome' in normal mode.", new RecordItemIndex(0));
            //Host.Local.OpenBrowser("https://asurequalitytest.crm6.dynamics.com/main.aspx", "chrome", "", false, false, false, false, false);
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.HomeButtonImageNavTabButtonImageSandbox' at 15;11.", repo.DashboardsAQCustomerServicesDashboa.HomeButtonImageNavTabButtonImageSandboxInfo, new RecordItemIndex(1));
            repo.DashboardsAQCustomerServicesDashboa.HomeButtonImageNavTabButtonImageSandbox.Click("15;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.NavActionButtonIcon' at 68;32.", repo.DashboardsAQCustomerServicesDashboa.NavActionButtonIconInfo, new RecordItemIndex(2));
            repo.DashboardsAQCustomerServicesDashboa.NavActionButtonIcon.Click("68;32");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.Accounts' at 9;6.", repo.DashboardsAQCustomerServicesDashboa.AccountsInfo, new RecordItemIndex(3));
            repo.DashboardsAQCustomerServicesDashboa.Accounts.Click("9;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.ContentIFrame0.CrmGridFindCriteria' at 10;14.", repo.DashboardsAQCustomerServicesDashboa.ContentIFrame0.CrmGridFindCriteriaInfo, new RecordItemIndex(4));
            repo.DashboardsAQCustomerServicesDashboa.ContentIFrame0.CrmGridFindCriteria.Click("10;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'westland{Space}milk' with focus on 'DashboardsAQCustomerServicesDashboa.ContentIFrame0.CrmGridFindCriteria'.", repo.DashboardsAQCustomerServicesDashboa.ContentIFrame0.CrmGridFindCriteriaInfo, new RecordItemIndex(5));
            repo.DashboardsAQCustomerServicesDashboa.ContentIFrame0.CrmGridFindCriteria.PressKeys("westland{Space}milk");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.ContentIFrame0.CrmGridFindCriteriaImg' at 5;10.", repo.DashboardsAQCustomerServicesDashboa.ContentIFrame0.CrmGridFindCriteriaImgInfo, new RecordItemIndex(6));
            repo.DashboardsAQCustomerServicesDashboa.ContentIFrame0.CrmGridFindCriteriaImg.Click("5;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.ContentIFrame0.WestlandCoOpDairyCoLtd' at 114;4.", repo.DashboardsAQCustomerServicesDashboa.ContentIFrame0.WestlandCoOpDairyCoLtdInfo, new RecordItemIndex(7));
            repo.DashboardsAQCustomerServicesDashboa.ContentIFrame0.WestlandCoOpDairyCoLtd.Click("114;4");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.ContentIFrame1.HttpsAsurequalitytestCrm6DynamicsC' at 3;9.", repo.DashboardsAQCustomerServicesDashboa.ContentIFrame1.HttpsAsurequalitytestCrm6DynamicsCInfo, new RecordItemIndex(8));
            repo.DashboardsAQCustomerServicesDashboa.ContentIFrame1.HttpsAsurequalitytestCrm6DynamicsC.Click("3;9");
            Delay.Milliseconds(200);
            
            // validate that the lock image exists on the customer name field ?
            Report.Log(ReportLevel.Info, "Validation", "validate that the lock image exists on the customer name field ?\r\nValidating ContainsImage (Screenshot: 'Screenshot1' with region {X=0,Y=0,Width=9,Height=12}) on item 'DashboardsAQCustomerServicesDashboa.ContentIFrame1.HttpsAsurequalitytestCrm6DynamicsC'.", repo.DashboardsAQCustomerServicesDashboa.ContentIFrame1.HttpsAsurequalitytestCrm6DynamicsCInfo, new RecordItemIndex(9));
            Validate.ContainsImage(repo.DashboardsAQCustomerServicesDashboa.ContentIFrame1.HttpsAsurequalitytestCrm6DynamicsCInfo, HttpsAsurequalitytestCrm6DynamicsC_Screenshot1, HttpsAsurequalitytestCrm6DynamicsC_Screenshot1_Options);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.ContentIFrame1.HttpsAsurequalitytestCrm6DynamicsC1' at 2;8.", repo.DashboardsAQCustomerServicesDashboa.ContentIFrame1.HttpsAsurequalitytestCrm6DynamicsC1Info, new RecordItemIndex(10));
            repo.DashboardsAQCustomerServicesDashboa.ContentIFrame1.HttpsAsurequalitytestCrm6DynamicsC1.Click("2;8");
            Delay.Milliseconds(200);
            
            // validate that the lock image exists on the TechOne id field
            Report.Log(ReportLevel.Info, "Validation", "validate that the lock image exists on the TechOne id field\r\nValidating ContainsImage (Screenshot: 'Screenshot1' with region {X=0,Y=0,Width=9,Height=12}) on item 'DashboardsAQCustomerServicesDashboa.ContentIFrame1.HttpsAsurequalitytestCrm6DynamicsC1'.", repo.DashboardsAQCustomerServicesDashboa.ContentIFrame1.HttpsAsurequalitytestCrm6DynamicsC1Info, new RecordItemIndex(11));
            Validate.ContainsImage(repo.DashboardsAQCustomerServicesDashboa.ContentIFrame1.HttpsAsurequalitytestCrm6DynamicsC1Info, HttpsAsurequalitytestCrm6DynamicsC1_Screenshot1, HttpsAsurequalitytestCrm6DynamicsC1_Screenshot1_Options);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.ContentIFrame1.FormSecNavigationControlIcon' at 9;14.", repo.DashboardsAQCustomerServicesDashboa.ContentIFrame1.FormSecNavigationControlIconInfo, new RecordItemIndex(12));
            repo.DashboardsAQCustomerServicesDashboa.ContentIFrame1.FormSecNavigationControlIcon.Click("9;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.ContentIFrame1.FlyoutFormSectionAnchor' at 16;10.", repo.DashboardsAQCustomerServicesDashboa.ContentIFrame1.FlyoutFormSectionAnchorInfo, new RecordItemIndex(13));
            repo.DashboardsAQCustomerServicesDashboa.ContentIFrame1.FlyoutFormSectionAnchor.Click("16;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.ContentIFrame1.HttpsAsurequalitytestCrm6DynamicsC2' at 3;10.", repo.DashboardsAQCustomerServicesDashboa.ContentIFrame1.HttpsAsurequalitytestCrm6DynamicsC2Info, new RecordItemIndex(14));
            repo.DashboardsAQCustomerServicesDashboa.ContentIFrame1.HttpsAsurequalitytestCrm6DynamicsC2.Click("3;10");
            Delay.Milliseconds(200);
            
            // validate that the lock image exists on the billing status field
            Report.Log(ReportLevel.Info, "Validation", "validate that the lock image exists on the billing status field\r\nValidating ContainsImage (Screenshot: 'Screenshot1' with region {X=0,Y=0,Width=9,Height=12}) on item 'DashboardsAQCustomerServicesDashboa.ContentIFrame1.HttpsAsurequalitytestCrm6DynamicsC2'.", repo.DashboardsAQCustomerServicesDashboa.ContentIFrame1.HttpsAsurequalitytestCrm6DynamicsC2Info, new RecordItemIndex(15));
            Validate.ContainsImage(repo.DashboardsAQCustomerServicesDashboa.ContentIFrame1.HttpsAsurequalitytestCrm6DynamicsC2Info, HttpsAsurequalitytestCrm6DynamicsC2_Screenshot1, HttpsAsurequalitytestCrm6DynamicsC2_Screenshot1_Options);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.Close' at 10;10.", repo.DashboardsAQCustomerServicesDashboa.CloseInfo, new RecordItemIndex(16));
            repo.DashboardsAQCustomerServicesDashboa.Close.Click("10;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.ContentIFrame0.CrmGridClearCriteriaImg' at 4;14.", repo.DashboardsAQCustomerServicesDashboa.ContentIFrame0.CrmGridClearCriteriaImgInfo, new RecordItemIndex(17));
            repo.DashboardsAQCustomerServicesDashboa.ContentIFrame0.CrmGridClearCriteriaImg.Click("4;14");
            Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AccountsAllAccountsMicrosoftDynami.Client' at 1567;12.", repo.AccountsAllAccountsMicrosoftDynami.ClientInfo, new RecordItemIndex(18));
            //repo.AccountsAllAccountsMicrosoftDynami.Client.Click("1567;12");
            //Delay.Milliseconds(200);
            
        }

#region Image Feature Data
        CompressedImage HttpsAsurequalitytestCrm6DynamicsC_Screenshot1
        { get { return repo.DashboardsAQCustomerServicesDashboa.ContentIFrame1.HttpsAsurequalitytestCrm6DynamicsCInfo.GetScreenshot1(new Rectangle(0, 0, 9, 12)); } }

        Imaging.FindOptions HttpsAsurequalitytestCrm6DynamicsC_Screenshot1_Options
        { get { return Imaging.FindOptions.Default; } }

        CompressedImage HttpsAsurequalitytestCrm6DynamicsC1_Screenshot1
        { get { return repo.DashboardsAQCustomerServicesDashboa.ContentIFrame1.HttpsAsurequalitytestCrm6DynamicsC1Info.GetScreenshot1(new Rectangle(0, 0, 9, 12)); } }

        Imaging.FindOptions HttpsAsurequalitytestCrm6DynamicsC1_Screenshot1_Options
        { get { return Imaging.FindOptions.Default; } }

        CompressedImage HttpsAsurequalitytestCrm6DynamicsC2_Screenshot1
        { get { return repo.DashboardsAQCustomerServicesDashboa.ContentIFrame1.HttpsAsurequalitytestCrm6DynamicsC2Info.GetScreenshot1(new Rectangle(0, 0, 9, 12)); } }

        Imaging.FindOptions HttpsAsurequalitytestCrm6DynamicsC2_Screenshot1_Options
        { get { return Imaging.FindOptions.Default; } }

#endregion
    }
#pragma warning restore 0436
}
