///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CRM
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Company_filled recording.
    /// </summary>
    [TestModule("29c17639-9acc-423f-b98d-8409f0c0c27e", ModuleType.Recording, 1)]
    public partial class Company_filled : ITestModule
    {
        /// <summary>
        /// Holds an instance of the CRMRepository repository.
        /// </summary>
        public static CRMRepository repo = CRMRepository.Instance;

        static Company_filled instance = new Company_filled();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Company_filled()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Company_filled Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            //Report.Log(ReportLevel.Info, "Website", "Opening web site 'https://asurequalitytest.crm6.dynamics.com/main.aspx' with browser 'chrome' in normal mode.", new RecordItemIndex(0));
            //Host.Local.OpenBrowser("https://asurequalitytest.crm6.dynamics.com/main.aspx", "chrome", "", false, false, false, false, false);
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.Sales1' at 2;7.", repo.DashboardsAQCustomerServicesDashboa.Sales1Info, new RecordItemIndex(1));
            repo.DashboardsAQCustomerServicesDashboa.Sales1.Click("2;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.Leads' at 1;9.", repo.DashboardsAQCustomerServicesDashboa.LeadsInfo, new RecordItemIndex(2));
            repo.DashboardsAQCustomerServicesDashboa.Leads.Click("1;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.ContentIFrame0.MyOpenLeads' at 140;17.", repo.DashboardsAQCustomerServicesDashboa.ContentIFrame0.MyOpenLeadsInfo, new RecordItemIndex(3));
            repo.DashboardsAQCustomerServicesDashboa.ContentIFrame0.MyOpenLeads.Click("140;17");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.ContentIFrame0.MyOpenLeads1' at 67;4.", repo.DashboardsAQCustomerServicesDashboa.ContentIFrame0.MyOpenLeads1Info, new RecordItemIndex(4));
            repo.DashboardsAQCustomerServicesDashboa.ContentIFrame0.MyOpenLeads1.Click("67;4");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.HttpsAsurequalitytestCrm6DynamicsC' at 14;4.", repo.DashboardsAQCustomerServicesDashboa.HttpsAsurequalitytestCrm6DynamicsCInfo, new RecordItemIndex(5));
            repo.DashboardsAQCustomerServicesDashboa.HttpsAsurequalitytestCrm6DynamicsC.Click("14;4");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.ContentIFrame1.SubjectI' at 76;13.", repo.DashboardsAQCustomerServicesDashboa.ContentIFrame1.SubjectIInfo, new RecordItemIndex(6));
            repo.DashboardsAQCustomerServicesDashboa.ContentIFrame1.SubjectI.Click("76;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LShiftKey down}t{LShiftKey up}est{Space}{LShiftKey down}L{LShiftKey up}ead{Return}' with focus on 'DashboardsAQCustomerServicesDashboa.ContentIFrame1.SubjectI'.", repo.DashboardsAQCustomerServicesDashboa.ContentIFrame1.SubjectIInfo, new RecordItemIndex(7));
            repo.DashboardsAQCustomerServicesDashboa.ContentIFrame1.SubjectI.PressKeys("{LShiftKey down}t{LShiftKey up}est{Space}{LShiftKey down}L{LShiftKey up}ead{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.ContentIFrame1.MsCrmInlineValueMsCrmInlineEditH' at 39;13.", repo.DashboardsAQCustomerServicesDashboa.ContentIFrame1.MsCrmInlineValueMsCrmInlineEditHInfo, new RecordItemIndex(8));
            repo.DashboardsAQCustomerServicesDashboa.ContentIFrame1.MsCrmInlineValueMsCrmInlineEditH.Click("39;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.ContentIFrame1.FullnameCompositionLinkControlFirstnam' at 52;15.", repo.DashboardsAQCustomerServicesDashboa.ContentIFrame1.FullnameCompositionLinkControlFirstnamInfo, new RecordItemIndex(9));
            repo.DashboardsAQCustomerServicesDashboa.ContentIFrame1.FullnameCompositionLinkControlFirstnam.Click("52;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LShiftKey down}B{LShiftKey up}ugs' with focus on 'DashboardsAQCustomerServicesDashboa.ContentIFrame1.FullnameCompositionLinkControlFirstnam'.", repo.DashboardsAQCustomerServicesDashboa.ContentIFrame1.FullnameCompositionLinkControlFirstnamInfo, new RecordItemIndex(10));
            repo.DashboardsAQCustomerServicesDashboa.ContentIFrame1.FullnameCompositionLinkControlFirstnam.PressKeys("{LShiftKey down}B{LShiftKey up}ugs");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.ContentIFrame1.MsCrmInlineValueMsCrmInlineEditH1' at 29;13.", repo.DashboardsAQCustomerServicesDashboa.ContentIFrame1.MsCrmInlineValueMsCrmInlineEditH1Info, new RecordItemIndex(11));
            repo.DashboardsAQCustomerServicesDashboa.ContentIFrame1.MsCrmInlineValueMsCrmInlineEditH1.Click("29;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LShiftKey down}B{LShiftKey up}unny'.", new RecordItemIndex(12));
            Keyboard.Press("{LShiftKey down}B{LShiftKey up}unny");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.ContentIFrame1.Done' at 12;5.", repo.DashboardsAQCustomerServicesDashboa.ContentIFrame1.DoneInfo, new RecordItemIndex(13));
            repo.DashboardsAQCustomerServicesDashboa.ContentIFrame1.Done.Click("12;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.ContentIFrame1.MsCrmInlineValueMsCrmInlineEditH2' at 26;14.", repo.DashboardsAQCustomerServicesDashboa.ContentIFrame1.MsCrmInlineValueMsCrmInlineEditH2Info, new RecordItemIndex(14));
            repo.DashboardsAQCustomerServicesDashboa.ContentIFrame1.MsCrmInlineValueMsCrmInlineEditH2.Click("26;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LShiftKey down}L{LShiftKey up}ooney{Space}{LShiftKey down}T{LShiftKey up}unes{Return}'.", new RecordItemIndex(15));
            Keyboard.Press("{LShiftKey down}L{LShiftKey up}ooney{Space}{LShiftKey down}T{LShiftKey up}unes{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.SpanTagSave1' at 10;10.", repo.DashboardsAQCustomerServicesDashboa.SpanTagSave1Info, new RecordItemIndex(16));
            repo.DashboardsAQCustomerServicesDashboa.SpanTagSave1.Click("10;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.SpanTagQualify' at 18;7.", repo.DashboardsAQCustomerServicesDashboa.SpanTagQualifyInfo, new RecordItemIndex(17));
            repo.DashboardsAQCustomerServicesDashboa.SpanTagQualify.Click("18;7");
            Delay.Milliseconds(200);
            
            // Validate that the error message box exists at this point
            Report.Log(ReportLevel.Info, "Validation", "Validate that the error message box exists at this point\r\nValidating Exists on item 'DashboardsAQCustomerServicesDashboa.InlineDialogIframe.DlgHdBodyContainer'.", repo.DashboardsAQCustomerServicesDashboa.InlineDialogIframe.DlgHdBodyContainerInfo, new RecordItemIndex(18));
            Validate.Exists(repo.DashboardsAQCustomerServicesDashboa.InlineDialogIframe.DlgHdBodyContainerInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.InlineDialogIframe.ButBegin' at 29;9.", repo.DashboardsAQCustomerServicesDashboa.InlineDialogIframe.ButBeginInfo, new RecordItemIndex(19));
            repo.DashboardsAQCustomerServicesDashboa.InlineDialogIframe.ButBegin.Click("29;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.HttpsAsurequalitytestCrm6DynamicsC1' at 8;10.", repo.DashboardsAQCustomerServicesDashboa.HttpsAsurequalitytestCrm6DynamicsC1Info, new RecordItemIndex(20));
            repo.DashboardsAQCustomerServicesDashboa.HttpsAsurequalitytestCrm6DynamicsC1.Click("8;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.SpanTagCanceled' at 36;5.", repo.DashboardsAQCustomerServicesDashboa.SpanTagCanceledInfo, new RecordItemIndex(21));
            repo.DashboardsAQCustomerServicesDashboa.SpanTagCanceled.Click("36;5");
            Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.Sales1' at 4;6.", repo.DashboardsAQCustomerServicesDashboa.Sales1Info, new RecordItemIndex(22));
            //repo.DashboardsAQCustomerServicesDashboa.Sales1.Click("4;6");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.Leads' at 5;12.", repo.DashboardsAQCustomerServicesDashboa.LeadsInfo, new RecordItemIndex(23));
            //repo.DashboardsAQCustomerServicesDashboa.Leads.Click("5;12");
            //Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
