///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CRM
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Create_button_available recording.
    /// </summary>
    [TestModule("d45cdf96-1ab2-4858-86a7-1f6ddf4e9b90", ModuleType.Recording, 1)]
    public partial class Create_button_available : ITestModule
    {
        /// <summary>
        /// Holds an instance of the CRMRepository repository.
        /// </summary>
        public static CRMRepository repo = CRMRepository.Instance;

        static Create_button_available instance = new Create_button_available();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Create_button_available()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Create_button_available Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            // Pre-req - Appropriate AD login to CRM active in the browser. Not browser windows open with CRM
            //Report.Log(ReportLevel.Info, "Website", "Pre-req - Appropriate AD login to CRM active in the browser. Not browser windows open with CRM\r\nOpening web site 'https://asurequalitytest.crm6.dynamics.com/main.aspx' with browser 'chrome' in maximized mode.", new RecordItemIndex(0));
            //Host.Local.OpenBrowser("https://asurequalitytest.crm6.dynamics.com/main.aspx", "chrome", "", false, true, false, false, false);
            //Delay.Milliseconds(0);
            
            // This tests goes to the account page and checks that the "new" bbbutton is present
            Report.Log(ReportLevel.Info, "Mouse", "This tests goes to the account page and checks that the \"new\" bbbutton is present\r\nMouse Left Click item 'DashboardsAQCustomerServicesDashboa.NavTabButtonImageContainer1' at 15;32.", repo.DashboardsAQCustomerServicesDashboa.NavTabButtonImageContainer1Info, new RecordItemIndex(1));
            repo.DashboardsAQCustomerServicesDashboa.NavTabButtonImageContainer1.Click("15;32");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.NavActionButtonIcon' at 84;33.", repo.DashboardsAQCustomerServicesDashboa.NavActionButtonIconInfo, new RecordItemIndex(2));
            repo.DashboardsAQCustomerServicesDashboa.NavActionButtonIcon.Click("84;33");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.Accounts' at 30;6.", repo.DashboardsAQCustomerServicesDashboa.AccountsInfo, new RecordItemIndex(3));
            repo.DashboardsAQCustomerServicesDashboa.Accounts.Click("30;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.ContentIFrame0.SomeDivTag' at 329;16.", repo.DashboardsAQCustomerServicesDashboa.ContentIFrame0.SomeDivTagInfo, new RecordItemIndex(4));
            repo.DashboardsAQCustomerServicesDashboa.ContentIFrame0.SomeDivTag.Click("329;16");
            Delay.Milliseconds(200);
            
            // validate that the new button exists
            Report.Log(ReportLevel.Info, "Validation", "validate that the new button exists\r\nValidating Exists on item 'DashboardsAQCustomerServicesDashboa.SpanTagNew'.", repo.DashboardsAQCustomerServicesDashboa.SpanTagNewInfo, new RecordItemIndex(5));
            Validate.Exists(repo.DashboardsAQCustomerServicesDashboa.SpanTagNewInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.SpanTagNew' at 22;14.", repo.DashboardsAQCustomerServicesDashboa.SpanTagNewInfo, new RecordItemIndex(6));
            repo.DashboardsAQCustomerServicesDashboa.SpanTagNew.Click("22;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.Close' at 3;8.", repo.DashboardsAQCustomerServicesDashboa.CloseInfo, new RecordItemIndex(7));
            repo.DashboardsAQCustomerServicesDashboa.Close.Click("3;8");
            Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AccountsAllAccountsMicrosoftDynami.Client' at 1563;11.", repo.AccountsAllAccountsMicrosoftDynami.ClientInfo, new RecordItemIndex(8));
            //repo.AccountsAllAccountsMicrosoftDynami.Client.Click("1563;11");
            //Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
