///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CRM
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CRM_adding_a_lead recording.
    /// </summary>
    [TestModule("bb80f846-bf1b-4113-965f-1827135fc4ae", ModuleType.Recording, 1)]
    public partial class CRM_adding_a_lead : ITestModule
    {
        /// <summary>
        /// Holds an instance of the CRMRepository repository.
        /// </summary>
        public static CRMRepository repo = CRMRepository.Instance;

        static CRM_adding_a_lead instance = new CRM_adding_a_lead();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CRM_adding_a_lead()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CRM_adding_a_lead Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'https://asurequalitytest.crm6.dynamics.com/main.aspx' with browser 'chrome' in normal mode.", new RecordItemIndex(0));
            Host.Local.OpenBrowser("https://asurequalitytest.crm6.dynamics.com/main.aspx", "chrome", "", false, false, false, false, false);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.NavTabGlobalCreateImage' at 11;4.", repo.DashboardsAQCustomerServicesDashboa.NavTabGlobalCreateImageInfo, new RecordItemIndex(1));
            repo.DashboardsAQCustomerServicesDashboa.NavTabGlobalCreateImage.Click("11;4");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.Lead' at 17;9.", repo.DashboardsAQCustomerServicesDashboa.LeadInfo, new RecordItemIndex(2));
            repo.DashboardsAQCustomerServicesDashboa.Lead.Click("17;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 5s for item 'DashboardsAQCustomerServicesDashboa.NavBarGloablQuickCreate.SubjectCl' to exist.", repo.DashboardsAQCustomerServicesDashboa.NavBarGloablQuickCreate.SubjectClInfo, new ActionTimeout(5000), new RecordItemIndex(3));
            repo.DashboardsAQCustomerServicesDashboa.NavBarGloablQuickCreate.SubjectClInfo.WaitForExists(5000);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'demo{Space}lead'.", new RecordItemIndex(4));
            Keyboard.Press("demo{Space}lead");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.NavBarGloablQuickCreate.MsCrmInlineValueMsCrmInlineEditHi' at 23;7.", repo.DashboardsAQCustomerServicesDashboa.NavBarGloablQuickCreate.MsCrmInlineValueMsCrmInlineEditHiInfo, new RecordItemIndex(5));
            repo.DashboardsAQCustomerServicesDashboa.NavBarGloablQuickCreate.MsCrmInlineValueMsCrmInlineEditHi.Click("23;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'test{Space}name'.", new RecordItemIndex(6));
            Keyboard.Press("test{Space}name");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.GlobalquickcreateSaveButtonNavBarGloa' at 24;8.", repo.DashboardsAQCustomerServicesDashboa.GlobalquickcreateSaveButtonNavBarGloaInfo, new RecordItemIndex(7));
            repo.DashboardsAQCustomerServicesDashboa.GlobalquickcreateSaveButtonNavBarGloa.Click("24;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'DashboardsAQCustomerServicesDashboa.SomeTdTag' at 144;3.", repo.DashboardsAQCustomerServicesDashboa.SomeTdTagInfo, new RecordItemIndex(8));
            repo.DashboardsAQCustomerServicesDashboa.SomeTdTag.MoveTo("144;3");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'DashboardsAQCustomerServicesDashboa.SomeTdTag' at 144;3.", repo.DashboardsAQCustomerServicesDashboa.SomeTdTagInfo, new RecordItemIndex(9));
            repo.DashboardsAQCustomerServicesDashboa.SomeTdTag.MoveTo("144;3");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'DashboardsAQCustomerServicesDashboa.SomeTdTag'.", repo.DashboardsAQCustomerServicesDashboa.SomeTdTagInfo, new RecordItemIndex(10));
            Validate.Exists(repo.DashboardsAQCustomerServicesDashboa.SomeTdTagInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Application", "Closing application containing item 'LeadTestNameGoogleChrome'.", repo.LeadTestNameGoogleChrome.SelfInfo, new RecordItemIndex(11));
            Host.Local.CloseApplication(repo.LeadTestNameGoogleChrome.Self, 100);
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LeadTestNameGoogleChrome.LeadTestName' at 65;8.", repo.LeadTestNameGoogleChrome.LeadTestNameInfo, new RecordItemIndex(12));
            //repo.LeadTestNameGoogleChrome.LeadTestName.Click("65;8");
            //Delay.Milliseconds(200);
            
            // dont use mouse to close  just use the kill application command more robust
            //Report.Log(ReportLevel.Info, "Mouse", "dont use mouse to close  just use the kill application command more robust\r\nMouse Left Click item 'LeadTestNameGoogleChrome.Close' at 10;13.", repo.LeadTestNameGoogleChrome.CloseInfo, new RecordItemIndex(13));
            //repo.LeadTestNameGoogleChrome.Close.Click("10;13");
            //Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
