///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CRM
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CRM_login recording.
    /// </summary>
    [TestModule("232bb703-abd3-4354-b971-15cf2572df49", ModuleType.Recording, 1)]
    public partial class CRM_login : ITestModule
    {
        /// <summary>
        /// Holds an instance of the CRMRepository repository.
        /// </summary>
        public static CRMRepository repo = CRMRepository.Instance;

        static CRM_login instance = new CRM_login();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CRM_login()
        {
            CRM_user_name = "asurequality.com{Tab}";
            Account_name = "Sunjeet Khokhar";
            Title = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CRM_login Instance
        {
            get { return instance; }
        }

#region Variables

        string _CRM_user_name;

        /// <summary>
        /// Gets or sets the value of variable CRM_user_name.
        /// </summary>
        [TestVariable("5cbad6ae-af49-4c32-b826-e5f70fc0dde9")]
        public string CRM_user_name
        {
            get { return _CRM_user_name; }
            set { _CRM_user_name = value; }
        }

        string _Account_name;

        /// <summary>
        /// Gets or sets the value of variable Account_name.
        /// </summary>
        [TestVariable("bd3ee648-96b6-4a20-bff4-2565d5173347")]
        public string Account_name
        {
            get { return _Account_name; }
            set { _Account_name = value; }
        }

        string _Title;

        /// <summary>
        /// Gets or sets the value of variable Title.
        /// </summary>
        [TestVariable("99a88f98-58d1-4689-9ae6-669d3aaf931b")]
        public string Title
        {
            get { return _Title; }
            set { _Title = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'https://asurequalitytest.crm6.dynamics.com/main.aspx' with browser 'chrome' in normal mode.", new RecordItemIndex(0));
            Host.Local.OpenBrowser("https://asurequalitytest.crm6.dynamics.com/main.aspx", "chrome", "", false, false, false, false, false);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SignInToYourAccount.UseAnotherAccount' at 28;32.", repo.SignInToYourAccount.UseAnotherAccountInfo, new RecordItemIndex(1));
            repo.SignInToYourAccount.UseAnotherAccount.Click("28;32");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SignInToYourAccount.CredUseridInputtext' at 20;15.", repo.SignInToYourAccount.CredUseridInputtextInfo, new RecordItemIndex(2));
            repo.SignInToYourAccount.CredUseridInputtext.Click("20;15");
            Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'sunjeet.khokhar{LShiftKey down}@{LShiftKey up}' with focus on 'SignInToYourAccount.CredUseridInputtext'.", repo.SignInToYourAccount.CredUseridInputtextInfo, new RecordItemIndex(3));
            //repo.SignInToYourAccount.CredUseridInputtext.PressKeys("sunjeet.khokhar{LShiftKey down}@{LShiftKey up}");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$CRM_user_name' with focus on 'SignInToYourAccount.CredUseridInputtext'.", repo.SignInToYourAccount.CredUseridInputtextInfo, new RecordItemIndex(4));
            repo.SignInToYourAccount.CredUseridInputtext.PressKeys(CRM_user_name);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{TAB}'.", new RecordItemIndex(5));
            Keyboard.Press("{TAB}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.NavBarUserInfoTextId' at 9;39.", repo.DashboardsAQCustomerServicesDashboa.NavBarUserInfoTextIdInfo, new RecordItemIndex(6));
            repo.DashboardsAQCustomerServicesDashboa.NavBarUserInfoTextId.Click("9;39");
            Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'Title' from item 'DashboardsAQCustomerServicesDashboa.Account_Name' and assigning its value to variable 'Title'.", repo.DashboardsAQCustomerServicesDashboa.Account_NameInfo, new RecordItemIndex(7));
            //Title = repo.DashboardsAQCustomerServicesDashboa.Account_Name.Element.GetAttributeValueText("Title");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Title=$Account_name) on item 'DashboardsAQCustomerServicesDashboa.Account_Name'.", repo.DashboardsAQCustomerServicesDashboa.Account_NameInfo, new RecordItemIndex(8));
            Validate.Attribute(repo.DashboardsAQCustomerServicesDashboa.Account_NameInfo, "Title", Account_name);
            Delay.Milliseconds(0);
            
            debug_comment();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.NavTabButtonUserInfoSignOutId' at 24;22.", repo.DashboardsAQCustomerServicesDashboa.NavTabButtonUserInfoSignOutIdInfo, new RecordItemIndex(10));
            repo.DashboardsAQCustomerServicesDashboa.NavTabButtonUserInfoSignOutId.Click("24;22");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa1.Close1' at 13;17.", repo.DashboardsAQCustomerServicesDashboa1.Close1Info, new RecordItemIndex(11));
            repo.DashboardsAQCustomerServicesDashboa1.Close1.Click("13;17");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
