///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace CRM
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the CRMRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
    [RepositoryFolder("d2449b8d-a71b-40ef-90fb-0bd7d816b0e7")]
    public partial class CRMRepository : RepoGenBaseFolder
    {
        static CRMRepository instance = new CRMRepository();
        CRMRepositoryFolders.AuditTraxAsureQualitysAuditTrackingAppFolder _audittraxasurequalitysaudittracking;
        CRMRepositoryFolders.DashboardsAQCustomerServicesDashboaAppFolder _dashboardsaqcustomerservicesdashboa;
        CRMRepositoryFolders.AccountFonterraAustraliaPtyLtdGoAppFolder _accountfonterraaustraliaptyltdgo;
        CRMRepositoryFolders.DashboardsAQCustomerServicesDashboa1AppFolder _dashboardsaqcustomerservicesdashboa1;
        CRMRepositoryFolders.SignInToYourAccountAppFolder _signintoyouraccount;

        /// <summary>
        /// Gets the singleton class instance representing the CRMRepository element repository.
        /// </summary>
        [RepositoryFolder("d2449b8d-a71b-40ef-90fb-0bd7d816b0e7")]
        public static CRMRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public CRMRepository() 
            : base("CRMRepository", "/", null, 0, false, "d2449b8d-a71b-40ef-90fb-0bd7d816b0e7", ".\\RepositoryImages\\CRMRepositoryd2449b8d.rximgres")
        {
            _audittraxasurequalitysaudittracking = new CRMRepositoryFolders.AuditTraxAsureQualitysAuditTrackingAppFolder(this);
            _dashboardsaqcustomerservicesdashboa = new CRMRepositoryFolders.DashboardsAQCustomerServicesDashboaAppFolder(this);
            _accountfonterraaustraliaptyltdgo = new CRMRepositoryFolders.AccountFonterraAustraliaPtyLtdGoAppFolder(this);
            _dashboardsaqcustomerservicesdashboa1 = new CRMRepositoryFolders.DashboardsAQCustomerServicesDashboa1AppFolder(this);
            _signintoyouraccount = new CRMRepositoryFolders.SignInToYourAccountAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("d2449b8d-a71b-40ef-90fb-0bd7d816b0e7")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The AuditTraxAsureQualitysAuditTracking folder.
        /// </summary>
        [RepositoryFolder("dae8ef5d-c899-40e9-9688-ad88564e2d97")]
        public virtual CRMRepositoryFolders.AuditTraxAsureQualitysAuditTrackingAppFolder AuditTraxAsureQualitysAuditTracking
        {
            get { return _audittraxasurequalitysaudittracking; }
        }

        /// <summary>
        /// The DashboardsAQCustomerServicesDashboa folder.
        /// </summary>
        [RepositoryFolder("ec76221a-af1b-4af6-ab9f-e3345e876442")]
        public virtual CRMRepositoryFolders.DashboardsAQCustomerServicesDashboaAppFolder DashboardsAQCustomerServicesDashboa
        {
            get { return _dashboardsaqcustomerservicesdashboa; }
        }

        /// <summary>
        /// The AccountFonterraAustraliaPtyLtdGo folder.
        /// </summary>
        [RepositoryFolder("c55acb7d-8dc3-4e7b-8e07-0c23edacd3ad")]
        public virtual CRMRepositoryFolders.AccountFonterraAustraliaPtyLtdGoAppFolder AccountFonterraAustraliaPtyLtdGo
        {
            get { return _accountfonterraaustraliaptyltdgo; }
        }

        /// <summary>
        /// The DashboardsAQCustomerServicesDashboa1 folder.
        /// </summary>
        [RepositoryFolder("4ae3f3ba-aab2-42a7-9a6a-bb2fb5cce140")]
        public virtual CRMRepositoryFolders.DashboardsAQCustomerServicesDashboa1AppFolder DashboardsAQCustomerServicesDashboa1
        {
            get { return _dashboardsaqcustomerservicesdashboa1; }
        }

        /// <summary>
        /// The SignInToYourAccount folder.
        /// </summary>
        [RepositoryFolder("0d94341e-3802-43ca-ae16-72f257924d98")]
        public virtual CRMRepositoryFolders.SignInToYourAccountAppFolder SignInToYourAccount
        {
            get { return _signintoyouraccount; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
    public partial class CRMRepositoryFolders
    {
        /// <summary>
        /// The AuditTraxAsureQualitysAuditTrackingAppFolder folder.
        /// </summary>
        [RepositoryFolder("dae8ef5d-c899-40e9-9688-ad88564e2d97")]
        public partial class AuditTraxAsureQualitysAuditTrackingAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _addressandsearchbarInfo;

            /// <summary>
            /// Creates a new AuditTraxAsureQualitysAuditTracking  folder.
            /// </summary>
            public AuditTraxAsureQualitysAuditTrackingAppFolder(RepoGenBaseFolder parentFolder) :
                    base("AuditTraxAsureQualitysAuditTracking", "/form[@title~'^auditTrax\\ -\\ AsureQuality''']", parentFolder, 30000, null, true, "dae8ef5d-c899-40e9-9688-ad88564e2d97", "")
            {
                _addressandsearchbarInfo = new RepoItemInfo(this, "AddressAndSearchBar", "container[@accessiblename='Google Chrome']//toolbar[@accessiblename='main']/?/?/text[@accessiblename='Address and search bar']", 30000, null, "595ffd7c-5925-4dad-bb56-ec1e455c002b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("dae8ef5d-c899-40e9-9688-ad88564e2d97")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("dae8ef5d-c899-40e9-9688-ad88564e2d97")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The AddressAndSearchBar item.
            /// </summary>
            [RepositoryItem("595ffd7c-5925-4dad-bb56-ec1e455c002b")]
            public virtual Ranorex.Text AddressAndSearchBar
            {
                get
                {
                    return _addressandsearchbarInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The AddressAndSearchBar item info.
            /// </summary>
            [RepositoryItemInfo("595ffd7c-5925-4dad-bb56-ec1e455c002b")]
            public virtual RepoItemInfo AddressAndSearchBarInfo
            {
                get
                {
                    return _addressandsearchbarInfo;
                }
            }
        }

        /// <summary>
        /// The DashboardsAQCustomerServicesDashboaAppFolder folder.
        /// </summary>
        [RepositoryFolder("ec76221a-af1b-4af6-ab9f-e3345e876442")]
        public partial class DashboardsAQCustomerServicesDashboaAppFolder : RepoGenBaseFolder
        {
            CRMRepositoryFolders.ContentIFrame0Folder _contentiframe0;
            CRMRepositoryFolders.ContentIFrame1Folder _contentiframe1;
            CRMRepositoryFolders.DashboardFrameFolder _dashboardframe;
            RepoItemInfo _salesInfo;
            RepoItemInfo _accountsInfo;
            RepoItemInfo _navtabbuttonimagecontainerInfo;
            RepoItemInfo _microsoftdynamicscrmmicrosoftdynamiInfo;
            RepoItemInfo _dvfooterInfo;
            RepoItemInfo _divtagdeleteInfo;
            RepoItemInfo _navbaruserinfotextidInfo;
            RepoItemInfo _navtabbuttonuserinfosignoutidInfo;
            RepoItemInfo _account_nameInfo;

            /// <summary>
            /// Creates a new DashboardsAQCustomerServicesDashboa  folder.
            /// </summary>
            public DashboardsAQCustomerServicesDashboaAppFolder(RepoGenBaseFolder parentFolder) :
                    base("DashboardsAQCustomerServicesDashboa", "/dom[@domain='asurequalitytest.crm6.dynamics.com']", parentFolder, 30000, null, false, "ec76221a-af1b-4af6-ab9f-e3345e876442", "")
            {
                _contentiframe0 = new CRMRepositoryFolders.ContentIFrame0Folder(this);
                _contentiframe1 = new CRMRepositoryFolders.ContentIFrame1Folder(this);
                _dashboardframe = new CRMRepositoryFolders.DashboardFrameFolder(this);
                _salesInfo = new RepoItemInfo(this, "Sales", ".//span[#'TabSFA']//img[@alt='Sales']", 30000, null, "601c89b2-f7a1-4ac1-b9cd-6b967a52696b");
                _accountsInfo = new RepoItemInfo(this, "Accounts", ".//a[#'nav_accts']/span[@innertext='Accounts']", 30000, null, "61925703-8798-4999-9558-d32efcb7ab9e");
                _navtabbuttonimagecontainerInfo = new RepoItemInfo(this, "NavTabButtonImageContainer", ".//span[#'TabSFA']/?/?/span", 30000, null, "53b878ce-1171-41d6-8624-18f3232ab303");
                _microsoftdynamicscrmmicrosoftdynamiInfo = new RepoItemInfo(this, "MicrosoftDynamicsCRMMicrosoftDynami", ".//span[#'navTabLogoTextId']/img[@alt~'^Microsoft\\ Dynamics\\ CRMM']", 30000, null, "edc9be02-5296-488d-b129-ae1ceaa3e7a1");
                _dvfooterInfo = new RepoItemInfo(this, "DvFooter", ".//iframe[#'InlineDialog_Iframe']//div[#'dvFooter']", 30000, null, "414a8e60-f977-4792-a9a5-97b52727bd2c");
                _divtagdeleteInfo = new RepoItemInfo(this, "DivTagDelete", ".//iframe[#'InlineDialog_Iframe']//button[#'butBegin']/div[@innertext=' Delete ']", 30000, null, "5c51316b-fcd8-4590-96e7-99548f8b57d6");
                _navbaruserinfotextidInfo = new RepoItemInfo(this, "NavBarUserInfoTextId", ".//span[#'navBarUserInfoTextId']", 30000, null, "2d74f326-1043-4719-bdce-1083f09dd8df");
                _navtabbuttonuserinfosignoutidInfo = new RepoItemInfo(this, "NavTabButtonUserInfoSignOutId", ".//a[#'navTabButtonUserInfoSignOutId']", 30000, null, "d5b99126-4c33-40fe-a8f1-fc0e4f94a69a");
                _account_nameInfo = new RepoItemInfo(this, "Account_Name", ".//span[#'navBarUserInfoTextId']/span[@title='Sunjeet Khokhar']", 30000, null, "f4905f95-745f-4645-9996-e382709bf5e1");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ec76221a-af1b-4af6-ab9f-e3345e876442")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ec76221a-af1b-4af6-ab9f-e3345e876442")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Sales item.
            /// </summary>
            [RepositoryItem("601c89b2-f7a1-4ac1-b9cd-6b967a52696b")]
            public virtual Ranorex.ImgTag Sales
            {
                get
                {
                    return _salesInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The Sales item info.
            /// </summary>
            [RepositoryItemInfo("601c89b2-f7a1-4ac1-b9cd-6b967a52696b")]
            public virtual RepoItemInfo SalesInfo
            {
                get
                {
                    return _salesInfo;
                }
            }

            /// <summary>
            /// The Accounts item.
            /// </summary>
            [RepositoryItem("61925703-8798-4999-9558-d32efcb7ab9e")]
            public virtual Ranorex.SpanTag Accounts
            {
                get
                {
                    return _accountsInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Accounts item info.
            /// </summary>
            [RepositoryItemInfo("61925703-8798-4999-9558-d32efcb7ab9e")]
            public virtual RepoItemInfo AccountsInfo
            {
                get
                {
                    return _accountsInfo;
                }
            }

            /// <summary>
            /// The NavTabButtonImageContainer item.
            /// </summary>
            [RepositoryItem("53b878ce-1171-41d6-8624-18f3232ab303")]
            public virtual Ranorex.SpanTag NavTabButtonImageContainer
            {
                get
                {
                    return _navtabbuttonimagecontainerInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The NavTabButtonImageContainer item info.
            /// </summary>
            [RepositoryItemInfo("53b878ce-1171-41d6-8624-18f3232ab303")]
            public virtual RepoItemInfo NavTabButtonImageContainerInfo
            {
                get
                {
                    return _navtabbuttonimagecontainerInfo;
                }
            }

            /// <summary>
            /// The MicrosoftDynamicsCRMMicrosoftDynami item.
            /// </summary>
            [RepositoryItem("edc9be02-5296-488d-b129-ae1ceaa3e7a1")]
            public virtual Ranorex.ImgTag MicrosoftDynamicsCRMMicrosoftDynami
            {
                get
                {
                    return _microsoftdynamicscrmmicrosoftdynamiInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The MicrosoftDynamicsCRMMicrosoftDynami item info.
            /// </summary>
            [RepositoryItemInfo("edc9be02-5296-488d-b129-ae1ceaa3e7a1")]
            public virtual RepoItemInfo MicrosoftDynamicsCRMMicrosoftDynamiInfo
            {
                get
                {
                    return _microsoftdynamicscrmmicrosoftdynamiInfo;
                }
            }

            /// <summary>
            /// The DvFooter item.
            /// </summary>
            [RepositoryItem("414a8e60-f977-4792-a9a5-97b52727bd2c")]
            public virtual Ranorex.DivTag DvFooter
            {
                get
                {
                    return _dvfooterInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The DvFooter item info.
            /// </summary>
            [RepositoryItemInfo("414a8e60-f977-4792-a9a5-97b52727bd2c")]
            public virtual RepoItemInfo DvFooterInfo
            {
                get
                {
                    return _dvfooterInfo;
                }
            }

            /// <summary>
            /// The DivTagDelete item.
            /// </summary>
            [RepositoryItem("5c51316b-fcd8-4590-96e7-99548f8b57d6")]
            public virtual Ranorex.DivTag DivTagDelete
            {
                get
                {
                    return _divtagdeleteInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The DivTagDelete item info.
            /// </summary>
            [RepositoryItemInfo("5c51316b-fcd8-4590-96e7-99548f8b57d6")]
            public virtual RepoItemInfo DivTagDeleteInfo
            {
                get
                {
                    return _divtagdeleteInfo;
                }
            }

            /// <summary>
            /// The NavBarUserInfoTextId item.
            /// </summary>
            [RepositoryItem("2d74f326-1043-4719-bdce-1083f09dd8df")]
            public virtual Ranorex.SpanTag NavBarUserInfoTextId
            {
                get
                {
                    return _navbaruserinfotextidInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The NavBarUserInfoTextId item info.
            /// </summary>
            [RepositoryItemInfo("2d74f326-1043-4719-bdce-1083f09dd8df")]
            public virtual RepoItemInfo NavBarUserInfoTextIdInfo
            {
                get
                {
                    return _navbaruserinfotextidInfo;
                }
            }

            /// <summary>
            /// The NavTabButtonUserInfoSignOutId item.
            /// </summary>
            [RepositoryItem("d5b99126-4c33-40fe-a8f1-fc0e4f94a69a")]
            public virtual Ranorex.ATag NavTabButtonUserInfoSignOutId
            {
                get
                {
                    return _navtabbuttonuserinfosignoutidInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The NavTabButtonUserInfoSignOutId item info.
            /// </summary>
            [RepositoryItemInfo("d5b99126-4c33-40fe-a8f1-fc0e4f94a69a")]
            public virtual RepoItemInfo NavTabButtonUserInfoSignOutIdInfo
            {
                get
                {
                    return _navtabbuttonuserinfosignoutidInfo;
                }
            }

            /// <summary>
            /// The Account_Name item.
            /// </summary>
            [RepositoryItem("f4905f95-745f-4645-9996-e382709bf5e1")]
            public virtual Ranorex.SpanTag Account_Name
            {
                get
                {
                    return _account_nameInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Account_Name item info.
            /// </summary>
            [RepositoryItemInfo("f4905f95-745f-4645-9996-e382709bf5e1")]
            public virtual RepoItemInfo Account_NameInfo
            {
                get
                {
                    return _account_nameInfo;
                }
            }

            /// <summary>
            /// The ContentIFrame0 folder.
            /// </summary>
            [RepositoryFolder("423da974-2a9c-4d3d-87eb-2702c14dbf0e")]
            public virtual CRMRepositoryFolders.ContentIFrame0Folder ContentIFrame0
            {
                get { return _contentiframe0; }
            }

            /// <summary>
            /// The ContentIFrame1 folder.
            /// </summary>
            [RepositoryFolder("7070dde7-71f6-4839-b4d4-e987eb003fd8")]
            public virtual CRMRepositoryFolders.ContentIFrame1Folder ContentIFrame1
            {
                get { return _contentiframe1; }
            }

            /// <summary>
            /// The DashboardFrame folder.
            /// </summary>
            [RepositoryFolder("da92a9af-c279-4110-9aef-e131ac158885")]
            public virtual CRMRepositoryFolders.DashboardFrameFolder DashboardFrame
            {
                get { return _dashboardframe; }
            }
        }

        /// <summary>
        /// The ContentIFrame0Folder folder.
        /// </summary>
        [RepositoryFolder("423da974-2a9c-4d3d-87eb-2702c14dbf0e")]
        public partial class ContentIFrame0Folder : RepoGenBaseFolder
        {
            RepoItemInfo _crmgriddivdataareaInfo;
            RepoItemInfo _crmgridfindcriteriaimgInfo;
            RepoItemInfo _crmgridfindcriteriaInfo;
            RepoItemInfo _fonterraaustraliaptyltdInfo;
            RepoItemInfo _sometdtagInfo;
            RepoItemInfo _sometdtag1Info;
            RepoItemInfo _crmgridclearcriteriaimgInfo;
            RepoItemInfo _westlandcoopdairycoltdInfo;

            /// <summary>
            /// Creates a new ContentIFrame0  folder.
            /// </summary>
            public ContentIFrame0Folder(RepoGenBaseFolder parentFolder) :
                    base("ContentIFrame0", ".//iframe[#'contentIFrame0']", parentFolder, 30000, null, false, "423da974-2a9c-4d3d-87eb-2702c14dbf0e", "")
            {
                _crmgriddivdataareaInfo = new RepoItemInfo(this, "CrmGridDivDataArea", ".//div[#'crmGrid_divDataArea']", 30000, null, "ca5d06ba-4bd4-467e-b4cb-acf122f3aa9f");
                _crmgridfindcriteriaimgInfo = new RepoItemInfo(this, "CrmGridFindCriteriaImg", ".//img[#'crmGrid_findCriteriaImg']", 30000, null, "82127ae7-bffb-4ecd-9000-0d5ea9d19b3c");
                _crmgridfindcriteriaInfo = new RepoItemInfo(this, "CrmGridFindCriteria", ".//input[#'crmGrid_findCriteria']", 30000, null, "05c4e5d2-0423-49a7-a82b-3c701e290582");
                _fonterraaustraliaptyltdInfo = new RepoItemInfo(this, "FonterraAustraliaPtyLtd", ".//table[#'gridBodyTable']/tbody/tr[41]//a[@innertext~'^Fonterra\\ Australia\\ Pty\\ Lt']", 30000, null, "c6a5cdc8-ce18-45be-abaa-f42b4e0b48a8");
                _sometdtagInfo = new RepoItemInfo(this, "SomeTdTag", ".//div[#'crmGrid_paneStripDiv']/?/?/table/tbody/tr[3]/td", 30000, null, "4546ae23-9bea-448d-9d96-9ae5fd28ac59");
                _sometdtag1Info = new RepoItemInfo(this, "SomeTdTag1", ".//div[#'crmGrid_splitTD']/?/?/table//td", 30000, null, "0d26e861-d558-4f1b-b1a1-b34798acd48b");
                _crmgridclearcriteriaimgInfo = new RepoItemInfo(this, "CrmGridClearCriteriaImg", ".//img[#'crmGrid_clearCriteriaImg']", 30000, null, "6ac0cd6c-b364-4c06-a8c0-91ad90be552a");
                _westlandcoopdairycoltdInfo = new RepoItemInfo(this, "WestlandCoOpDairyCoLtd", ".//table[#'gridBodyTable']/tbody/tr[8]/td[4]/?/?/a[@innertext~'^Westland\\ Co-op\\ Dairy\\ co\\ L']", 30000, null, "414eb5da-b3cd-44d5-9387-3805ac152110");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("423da974-2a9c-4d3d-87eb-2702c14dbf0e")]
            public virtual Ranorex.IFrameTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.IFrameTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("423da974-2a9c-4d3d-87eb-2702c14dbf0e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The CrmGridDivDataArea item.
            /// </summary>
            [RepositoryItem("ca5d06ba-4bd4-467e-b4cb-acf122f3aa9f")]
            public virtual Ranorex.DivTag CrmGridDivDataArea
            {
                get
                {
                    return _crmgriddivdataareaInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The CrmGridDivDataArea item info.
            /// </summary>
            [RepositoryItemInfo("ca5d06ba-4bd4-467e-b4cb-acf122f3aa9f")]
            public virtual RepoItemInfo CrmGridDivDataAreaInfo
            {
                get
                {
                    return _crmgriddivdataareaInfo;
                }
            }

            /// <summary>
            /// The CrmGridFindCriteriaImg item.
            /// </summary>
            [RepositoryItem("82127ae7-bffb-4ecd-9000-0d5ea9d19b3c")]
            public virtual Ranorex.ImgTag CrmGridFindCriteriaImg
            {
                get
                {
                    return _crmgridfindcriteriaimgInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The CrmGridFindCriteriaImg item info.
            /// </summary>
            [RepositoryItemInfo("82127ae7-bffb-4ecd-9000-0d5ea9d19b3c")]
            public virtual RepoItemInfo CrmGridFindCriteriaImgInfo
            {
                get
                {
                    return _crmgridfindcriteriaimgInfo;
                }
            }

            /// <summary>
            /// The CrmGridFindCriteria item.
            /// </summary>
            [RepositoryItem("05c4e5d2-0423-49a7-a82b-3c701e290582")]
            public virtual Ranorex.InputTag CrmGridFindCriteria
            {
                get
                {
                    return _crmgridfindcriteriaInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The CrmGridFindCriteria item info.
            /// </summary>
            [RepositoryItemInfo("05c4e5d2-0423-49a7-a82b-3c701e290582")]
            public virtual RepoItemInfo CrmGridFindCriteriaInfo
            {
                get
                {
                    return _crmgridfindcriteriaInfo;
                }
            }

            /// <summary>
            /// The FonterraAustraliaPtyLtd item.
            /// </summary>
            [RepositoryItem("c6a5cdc8-ce18-45be-abaa-f42b4e0b48a8")]
            public virtual Ranorex.ATag FonterraAustraliaPtyLtd
            {
                get
                {
                    return _fonterraaustraliaptyltdInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The FonterraAustraliaPtyLtd item info.
            /// </summary>
            [RepositoryItemInfo("c6a5cdc8-ce18-45be-abaa-f42b4e0b48a8")]
            public virtual RepoItemInfo FonterraAustraliaPtyLtdInfo
            {
                get
                {
                    return _fonterraaustraliaptyltdInfo;
                }
            }

            /// <summary>
            /// The SomeTdTag item.
            /// </summary>
            [RepositoryItem("4546ae23-9bea-448d-9d96-9ae5fd28ac59")]
            public virtual Ranorex.TdTag SomeTdTag
            {
                get
                {
                    return _sometdtagInfo.CreateAdapter<Ranorex.TdTag>(true);
                }
            }

            /// <summary>
            /// The SomeTdTag item info.
            /// </summary>
            [RepositoryItemInfo("4546ae23-9bea-448d-9d96-9ae5fd28ac59")]
            public virtual RepoItemInfo SomeTdTagInfo
            {
                get
                {
                    return _sometdtagInfo;
                }
            }

            /// <summary>
            /// The SomeTdTag1 item.
            /// </summary>
            [RepositoryItem("0d26e861-d558-4f1b-b1a1-b34798acd48b")]
            public virtual Ranorex.TdTag SomeTdTag1
            {
                get
                {
                    return _sometdtag1Info.CreateAdapter<Ranorex.TdTag>(true);
                }
            }

            /// <summary>
            /// The SomeTdTag1 item info.
            /// </summary>
            [RepositoryItemInfo("0d26e861-d558-4f1b-b1a1-b34798acd48b")]
            public virtual RepoItemInfo SomeTdTag1Info
            {
                get
                {
                    return _sometdtag1Info;
                }
            }

            /// <summary>
            /// The CrmGridClearCriteriaImg item.
            /// </summary>
            [RepositoryItem("6ac0cd6c-b364-4c06-a8c0-91ad90be552a")]
            public virtual Ranorex.ImgTag CrmGridClearCriteriaImg
            {
                get
                {
                    return _crmgridclearcriteriaimgInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The CrmGridClearCriteriaImg item info.
            /// </summary>
            [RepositoryItemInfo("6ac0cd6c-b364-4c06-a8c0-91ad90be552a")]
            public virtual RepoItemInfo CrmGridClearCriteriaImgInfo
            {
                get
                {
                    return _crmgridclearcriteriaimgInfo;
                }
            }

            /// <summary>
            /// The WestlandCoOpDairyCoLtd item.
            /// </summary>
            [RepositoryItem("414eb5da-b3cd-44d5-9387-3805ac152110")]
            public virtual Ranorex.ATag WestlandCoOpDairyCoLtd
            {
                get
                {
                    return _westlandcoopdairycoltdInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The WestlandCoOpDairyCoLtd item info.
            /// </summary>
            [RepositoryItemInfo("414eb5da-b3cd-44d5-9387-3805ac152110")]
            public virtual RepoItemInfo WestlandCoOpDairyCoLtdInfo
            {
                get
                {
                    return _westlandcoopdairycoltdInfo;
                }
            }
        }

        /// <summary>
        /// The ContentIFrame1Folder folder.
        /// </summary>
        [RepositoryFolder("7070dde7-71f6-4839-b4d4-e987eb003fd8")]
        public partial class ContentIFrame1Folder : RepoGenBaseFolder
        {
            RepoItemInfo _activitylabelinlineactivitybar4212Info;
            RepoItemInfo _spantagokInfo;
            RepoItemInfo _tdareasInfo;
            RepoItemInfo _divtag298662bc2f8ce61180e8c4346bc5cInfo;
            RepoItemInfo _quickcreateactivity4212controlidsubjectInfo;
            RepoItemInfo _contentnotescontrolInfo;
            RepoItemInfo _tabletag7a073b7c542224183d26b2a7eb2Info;
            RepoItemInfo _save4212quickcreatebuttonInfo;
            RepoItemInfo _fonterraaustraliaptyltdInfo;
            RepoItemInfo _subjectlabelInfo;

            /// <summary>
            /// Creates a new ContentIFrame1  folder.
            /// </summary>
            public ContentIFrame1Folder(RepoGenBaseFolder parentFolder) :
                    base("ContentIFrame1", ".//iframe[#'contentIFrame1']", parentFolder, 30000, null, false, "7070dde7-71f6-4839-b4d4-e987eb003fd8", "")
            {
                _activitylabelinlineactivitybar4212Info = new RepoItemInfo(this, "ActivityLabelinlineactivitybar4212", ".//a[#'activityLabelinlineactivitybar4212']", 30000, null, "1cda8ac7-ae67-4670-b7b7-cbe4a800f9a4");
                _spantagokInfo = new RepoItemInfo(this, "SpanTagOK", ".//button[#'save4212QuickCreateButton']/span[@innertext='OK']", 30000, null, "395f8a90-fde3-4c5d-8bfd-1625a0a3f926");
                _tdareasInfo = new RepoItemInfo(this, "TdAreas", ".//div[#'tdAreas']", 30000, null, "ef50671c-33bb-4109-90c8-e2a527d7d546");
                _divtag298662bc2f8ce61180e8c4346bc5cInfo = new RepoItemInfo(this, "DivTag298662BC2F8CE61180E8C4346BC5C", ".//div[#'{298662BC-2F8C-E611-80E8-C4346BC5C274}_text']", 30000, null, "8dca59df-82b6-44d3-8811-75e0a646a720");
                _quickcreateactivity4212controlidsubjectInfo = new RepoItemInfo(this, "QuickCreateActivity4212controlIdSubject", ".//input[#'quickCreateActivity4212controlId_subject_i']", 30000, null, "c8ff8079-561e-4584-a56f-aa55dcd2ab76");
                _contentnotescontrolInfo = new RepoItemInfo(this, "ContentNotescontrol", ".//div[#'content_notescontrol']", 30000, null, "cdd0fbf8-d6b8-45b1-9624-9a031a813e5c");
                _tabletag7a073b7c542224183d26b2a7eb2Info = new RepoItemInfo(this, "TableTag7a073b7c542224183d26B2a7eb2", ".//table[#'{7a073b7c-5422-2418-3d26-b2a7eb290832}']", 30000, null, "8ea75671-9c91-4ece-9728-7921d7a8153b");
                _save4212quickcreatebuttonInfo = new RepoItemInfo(this, "Save4212QuickCreateButton", ".//button[#'save4212QuickCreateButton']", 30000, null, "de7b943c-20c7-40e6-af80-11843e627013");
                _fonterraaustraliaptyltdInfo = new RepoItemInfo(this, "FonterraAustraliaPtyLtd", ".//div[#'FormTitle']/h1[@title~'^Fonterra\\ Australia\\ Pty\\ Lt']", 30000, null, "03357a4f-7e39-4389-99e3-9166b451785c");
                _subjectlabelInfo = new RepoItemInfo(this, "SubjectLabel", ".//label[#'Subject_label']", 30000, null, "26ef0876-1035-46e9-8900-9bbab98631b0");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("7070dde7-71f6-4839-b4d4-e987eb003fd8")]
            public virtual Ranorex.IFrameTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.IFrameTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("7070dde7-71f6-4839-b4d4-e987eb003fd8")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ActivityLabelinlineactivitybar4212 item.
            /// </summary>
            [RepositoryItem("1cda8ac7-ae67-4670-b7b7-cbe4a800f9a4")]
            public virtual Ranorex.ATag ActivityLabelinlineactivitybar4212
            {
                get
                {
                    return _activitylabelinlineactivitybar4212Info.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ActivityLabelinlineactivitybar4212 item info.
            /// </summary>
            [RepositoryItemInfo("1cda8ac7-ae67-4670-b7b7-cbe4a800f9a4")]
            public virtual RepoItemInfo ActivityLabelinlineactivitybar4212Info
            {
                get
                {
                    return _activitylabelinlineactivitybar4212Info;
                }
            }

            /// <summary>
            /// The SpanTagOK item.
            /// </summary>
            [RepositoryItem("395f8a90-fde3-4c5d-8bfd-1625a0a3f926")]
            public virtual Ranorex.SpanTag SpanTagOK
            {
                get
                {
                    return _spantagokInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The SpanTagOK item info.
            /// </summary>
            [RepositoryItemInfo("395f8a90-fde3-4c5d-8bfd-1625a0a3f926")]
            public virtual RepoItemInfo SpanTagOKInfo
            {
                get
                {
                    return _spantagokInfo;
                }
            }

            /// <summary>
            /// The TdAreas item.
            /// </summary>
            [RepositoryItem("ef50671c-33bb-4109-90c8-e2a527d7d546")]
            public virtual Ranorex.DivTag TdAreas
            {
                get
                {
                    return _tdareasInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The TdAreas item info.
            /// </summary>
            [RepositoryItemInfo("ef50671c-33bb-4109-90c8-e2a527d7d546")]
            public virtual RepoItemInfo TdAreasInfo
            {
                get
                {
                    return _tdareasInfo;
                }
            }

            /// <summary>
            /// The DivTag298662BC2F8CE61180E8C4346BC5C item.
            /// </summary>
            [RepositoryItem("8dca59df-82b6-44d3-8811-75e0a646a720")]
            public virtual Ranorex.DivTag DivTag298662BC2F8CE61180E8C4346BC5C
            {
                get
                {
                    return _divtag298662bc2f8ce61180e8c4346bc5cInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The DivTag298662BC2F8CE61180E8C4346BC5C item info.
            /// </summary>
            [RepositoryItemInfo("8dca59df-82b6-44d3-8811-75e0a646a720")]
            public virtual RepoItemInfo DivTag298662BC2F8CE61180E8C4346BC5CInfo
            {
                get
                {
                    return _divtag298662bc2f8ce61180e8c4346bc5cInfo;
                }
            }

            /// <summary>
            /// The QuickCreateActivity4212controlIdSubject item.
            /// </summary>
            [RepositoryItem("c8ff8079-561e-4584-a56f-aa55dcd2ab76")]
            public virtual Ranorex.InputTag QuickCreateActivity4212controlIdSubject
            {
                get
                {
                    return _quickcreateactivity4212controlidsubjectInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The QuickCreateActivity4212controlIdSubject item info.
            /// </summary>
            [RepositoryItemInfo("c8ff8079-561e-4584-a56f-aa55dcd2ab76")]
            public virtual RepoItemInfo QuickCreateActivity4212controlIdSubjectInfo
            {
                get
                {
                    return _quickcreateactivity4212controlidsubjectInfo;
                }
            }

            /// <summary>
            /// The ContentNotescontrol item.
            /// </summary>
            [RepositoryItem("cdd0fbf8-d6b8-45b1-9624-9a031a813e5c")]
            public virtual Ranorex.DivTag ContentNotescontrol
            {
                get
                {
                    return _contentnotescontrolInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ContentNotescontrol item info.
            /// </summary>
            [RepositoryItemInfo("cdd0fbf8-d6b8-45b1-9624-9a031a813e5c")]
            public virtual RepoItemInfo ContentNotescontrolInfo
            {
                get
                {
                    return _contentnotescontrolInfo;
                }
            }

            /// <summary>
            /// The TableTag7a073b7c542224183d26B2a7eb2 item.
            /// </summary>
            [RepositoryItem("8ea75671-9c91-4ece-9728-7921d7a8153b")]
            public virtual Ranorex.TableTag TableTag7a073b7c542224183d26B2a7eb2
            {
                get
                {
                    return _tabletag7a073b7c542224183d26b2a7eb2Info.CreateAdapter<Ranorex.TableTag>(true);
                }
            }

            /// <summary>
            /// The TableTag7a073b7c542224183d26B2a7eb2 item info.
            /// </summary>
            [RepositoryItemInfo("8ea75671-9c91-4ece-9728-7921d7a8153b")]
            public virtual RepoItemInfo TableTag7a073b7c542224183d26B2a7eb2Info
            {
                get
                {
                    return _tabletag7a073b7c542224183d26b2a7eb2Info;
                }
            }

            /// <summary>
            /// The Save4212QuickCreateButton item.
            /// </summary>
            [RepositoryItem("de7b943c-20c7-40e6-af80-11843e627013")]
            public virtual Ranorex.ButtonTag Save4212QuickCreateButton
            {
                get
                {
                    return _save4212quickcreatebuttonInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The Save4212QuickCreateButton item info.
            /// </summary>
            [RepositoryItemInfo("de7b943c-20c7-40e6-af80-11843e627013")]
            public virtual RepoItemInfo Save4212QuickCreateButtonInfo
            {
                get
                {
                    return _save4212quickcreatebuttonInfo;
                }
            }

            /// <summary>
            /// The FonterraAustraliaPtyLtd item.
            /// </summary>
            [RepositoryItem("03357a4f-7e39-4389-99e3-9166b451785c")]
            public virtual Ranorex.H1Tag FonterraAustraliaPtyLtd
            {
                get
                {
                    return _fonterraaustraliaptyltdInfo.CreateAdapter<Ranorex.H1Tag>(true);
                }
            }

            /// <summary>
            /// The FonterraAustraliaPtyLtd item info.
            /// </summary>
            [RepositoryItemInfo("03357a4f-7e39-4389-99e3-9166b451785c")]
            public virtual RepoItemInfo FonterraAustraliaPtyLtdInfo
            {
                get
                {
                    return _fonterraaustraliaptyltdInfo;
                }
            }

            /// <summary>
            /// The SubjectLabel item.
            /// </summary>
            [RepositoryItem("26ef0876-1035-46e9-8900-9bbab98631b0")]
            public virtual Ranorex.LabelTag SubjectLabel
            {
                get
                {
                    return _subjectlabelInfo.CreateAdapter<Ranorex.LabelTag>(true);
                }
            }

            /// <summary>
            /// The SubjectLabel item info.
            /// </summary>
            [RepositoryItemInfo("26ef0876-1035-46e9-8900-9bbab98631b0")]
            public virtual RepoItemInfo SubjectLabelInfo
            {
                get
                {
                    return _subjectlabelInfo;
                }
            }
        }

        /// <summary>
        /// The DashboardFrameFolder folder.
        /// </summary>
        [RepositoryFolder("da92a9af-c279-4110-9aef-e131ac158885")]
        public partial class DashboardFrameFolder : RepoGenBaseFolder
        {
            RepoItemInfo _component90b0b4afindcriteriaimgInfo;
            RepoItemInfo _component90b0b4afindcriteriaInfo;
            RepoItemInfo _nobr1Info;
            RepoItemInfo _taskInfo;
            RepoItemInfo _nobrInfo;
            RepoItemInfo _httpsasurequalitytestcrm6dynamicscInfo;

            /// <summary>
            /// Creates a new DashboardFrame  folder.
            /// </summary>
            public DashboardFrameFolder(RepoGenBaseFolder parentFolder) :
                    base("DashboardFrame", ".//iframe[#'contentIFrame2']//iframe[#'dashboardFrame']", parentFolder, 30000, null, false, "da92a9af-c279-4110-9aef-e131ac158885", "")
            {
                _component90b0b4afindcriteriaimgInfo = new RepoItemInfo(this, "Component90b0b4aFindCriteriaImg", ".//img[#'Component90b0b4a_findCriteriaImg']", 30000, null, "7892e1ba-ac6a-4d3a-981b-b4266e290898");
                _component90b0b4afindcriteriaInfo = new RepoItemInfo(this, "Component90b0b4aFindCriteria", ".//input[#'Component90b0b4a_findCriteria']", 30000, null, "96223447-abfe-4c16-bd91-5a97fb9787a5");
                _nobr1Info = new RepoItemInfo(this, "Nobr1", ".//table[#'gridBodyTable']//tag[@tagname='nobr']", 30000, null, "e13bbb55-ea46-4229-9a3f-059666563ef0");
                _taskInfo = new RepoItemInfo(this, "Task", ".//table[#'gridBodyTable']/tbody/tr[5]/td[3]/tag[@tagname='nobr']/span[@innertext='Task']", 30000, null, "8d5ed629-18bd-4d66-92e8-7bb0bff94c45");
                _nobrInfo = new RepoItemInfo(this, "Nobr", ".//table[#'gridBodyTable']/tbody/tr[5]/td[4]/tag[@tagname='nobr']", 30000, null, "52c4dd5c-e858-45a6-83aa-25d6eeccc629");
                _httpsasurequalitytestcrm6dynamicscInfo = new RepoItemInfo(this, "HttpsAsurequalitytestCrm6DynamicsC", ".//td[#'gridBodyTable_gridDelBtn_0']//img[@alt='']", 30000, null, "9946e03a-3a14-4da5-b52d-a1b1b6429faa");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("da92a9af-c279-4110-9aef-e131ac158885")]
            public virtual Ranorex.IFrameTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.IFrameTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("da92a9af-c279-4110-9aef-e131ac158885")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Component90b0b4aFindCriteriaImg item.
            /// </summary>
            [RepositoryItem("7892e1ba-ac6a-4d3a-981b-b4266e290898")]
            public virtual Ranorex.ImgTag Component90b0b4aFindCriteriaImg
            {
                get
                {
                    return _component90b0b4afindcriteriaimgInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The Component90b0b4aFindCriteriaImg item info.
            /// </summary>
            [RepositoryItemInfo("7892e1ba-ac6a-4d3a-981b-b4266e290898")]
            public virtual RepoItemInfo Component90b0b4aFindCriteriaImgInfo
            {
                get
                {
                    return _component90b0b4afindcriteriaimgInfo;
                }
            }

            /// <summary>
            /// The Component90b0b4aFindCriteria item.
            /// </summary>
            [RepositoryItem("96223447-abfe-4c16-bd91-5a97fb9787a5")]
            public virtual Ranorex.InputTag Component90b0b4aFindCriteria
            {
                get
                {
                    return _component90b0b4afindcriteriaInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Component90b0b4aFindCriteria item info.
            /// </summary>
            [RepositoryItemInfo("96223447-abfe-4c16-bd91-5a97fb9787a5")]
            public virtual RepoItemInfo Component90b0b4aFindCriteriaInfo
            {
                get
                {
                    return _component90b0b4afindcriteriaInfo;
                }
            }

            /// <summary>
            /// The Nobr1 item.
            /// </summary>
            [RepositoryItem("e13bbb55-ea46-4229-9a3f-059666563ef0")]
            public virtual Ranorex.WebElement Nobr1
            {
                get
                {
                    return _nobr1Info.CreateAdapter<Ranorex.WebElement>(true);
                }
            }

            /// <summary>
            /// The Nobr1 item info.
            /// </summary>
            [RepositoryItemInfo("e13bbb55-ea46-4229-9a3f-059666563ef0")]
            public virtual RepoItemInfo Nobr1Info
            {
                get
                {
                    return _nobr1Info;
                }
            }

            /// <summary>
            /// The Task item.
            /// </summary>
            [RepositoryItem("8d5ed629-18bd-4d66-92e8-7bb0bff94c45")]
            public virtual Ranorex.SpanTag Task
            {
                get
                {
                    return _taskInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Task item info.
            /// </summary>
            [RepositoryItemInfo("8d5ed629-18bd-4d66-92e8-7bb0bff94c45")]
            public virtual RepoItemInfo TaskInfo
            {
                get
                {
                    return _taskInfo;
                }
            }

            /// <summary>
            /// The Nobr item.
            /// </summary>
            [RepositoryItem("52c4dd5c-e858-45a6-83aa-25d6eeccc629")]
            public virtual Ranorex.WebElement Nobr
            {
                get
                {
                    return _nobrInfo.CreateAdapter<Ranorex.WebElement>(true);
                }
            }

            /// <summary>
            /// The Nobr item info.
            /// </summary>
            [RepositoryItemInfo("52c4dd5c-e858-45a6-83aa-25d6eeccc629")]
            public virtual RepoItemInfo NobrInfo
            {
                get
                {
                    return _nobrInfo;
                }
            }

            /// <summary>
            /// The HttpsAsurequalitytestCrm6DynamicsC item.
            /// </summary>
            [RepositoryItem("9946e03a-3a14-4da5-b52d-a1b1b6429faa")]
            public virtual Ranorex.ImgTag HttpsAsurequalitytestCrm6DynamicsC
            {
                get
                {
                    return _httpsasurequalitytestcrm6dynamicscInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The HttpsAsurequalitytestCrm6DynamicsC item info.
            /// </summary>
            [RepositoryItemInfo("9946e03a-3a14-4da5-b52d-a1b1b6429faa")]
            public virtual RepoItemInfo HttpsAsurequalitytestCrm6DynamicsCInfo
            {
                get
                {
                    return _httpsasurequalitytestcrm6dynamicscInfo;
                }
            }
        }

        /// <summary>
        /// The AccountFonterraAustraliaPtyLtdGoAppFolder folder.
        /// </summary>
        [RepositoryFolder("c55acb7d-8dc3-4e7b-8e07-0c23edacd3ad")]
        public partial class AccountFonterraAustraliaPtyLtdGoAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _closeInfo;

            /// <summary>
            /// Creates a new AccountFonterraAustraliaPtyLtdGo  folder.
            /// </summary>
            public AccountFonterraAustraliaPtyLtdGoAppFolder(RepoGenBaseFolder parentFolder) :
                    base("AccountFonterraAustraliaPtyLtdGo", "/form[@title~'^Account:\\ Fonterra\\ Austral']", parentFolder, 30000, null, true, "c55acb7d-8dc3-4e7b-8e07-0c23edacd3ad", "")
            {
                _closeInfo = new RepoItemInfo(this, "Close", "container[@accessiblename='Google Chrome']//tabpage[@accessiblename~'^Account:\\ Fonterra\\ Austral']/button[@accessiblename='Close']", 30000, null, "6c3b294c-9d9b-4305-98ef-3e9e4b5e3de7");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c55acb7d-8dc3-4e7b-8e07-0c23edacd3ad")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c55acb7d-8dc3-4e7b-8e07-0c23edacd3ad")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("6c3b294c-9d9b-4305-98ef-3e9e4b5e3de7")]
            public virtual Ranorex.Button Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("6c3b294c-9d9b-4305-98ef-3e9e4b5e3de7")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }
        }

        /// <summary>
        /// The DashboardsAQCustomerServicesDashboa1AppFolder folder.
        /// </summary>
        [RepositoryFolder("4ae3f3ba-aab2-42a7-9a6a-bb2fb5cce140")]
        public partial class DashboardsAQCustomerServicesDashboa1AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _closeInfo;
            RepoItemInfo _close1Info;

            /// <summary>
            /// Creates a new DashboardsAQCustomerServicesDashboa1  folder.
            /// </summary>
            public DashboardsAQCustomerServicesDashboa1AppFolder(RepoGenBaseFolder parentFolder) :
                    base("DashboardsAQCustomerServicesDashboa1", "/form[@title~'^Dashboards:\\ AQ\\ Customer\\ S']", parentFolder, 30000, null, true, "4ae3f3ba-aab2-42a7-9a6a-bb2fb5cce140", "")
            {
                _closeInfo = new RepoItemInfo(this, "Close", "container[@accessiblename='Google Chrome']//tabpage[@accessiblename~'^Dashboards:\\ AQ\\ Customer\\ S']/button[@accessiblename='Close']", 30000, null, "c6e53b4b-6b96-4786-948e-4ec769907ce6");
                _close1Info = new RepoItemInfo(this, "Close1", "container[@accessiblename='Google Chrome']//tabpage[@accessiblename='Sign out']/button[@accessiblename='Close']", 30000, null, "daf8ed33-060a-4a10-9509-6119c844d8d0");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("4ae3f3ba-aab2-42a7-9a6a-bb2fb5cce140")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("4ae3f3ba-aab2-42a7-9a6a-bb2fb5cce140")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("c6e53b4b-6b96-4786-948e-4ec769907ce6")]
            public virtual Ranorex.Button Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("c6e53b4b-6b96-4786-948e-4ec769907ce6")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }

            /// <summary>
            /// The Close1 item.
            /// </summary>
            [RepositoryItem("daf8ed33-060a-4a10-9509-6119c844d8d0")]
            public virtual Ranorex.Button Close1
            {
                get
                {
                    return _close1Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Close1 item info.
            /// </summary>
            [RepositoryItemInfo("daf8ed33-060a-4a10-9509-6119c844d8d0")]
            public virtual RepoItemInfo Close1Info
            {
                get
                {
                    return _close1Info;
                }
            }
        }

        /// <summary>
        /// The SignInToYourAccountAppFolder folder.
        /// </summary>
        [RepositoryFolder("0d94341e-3802-43ca-ae16-72f257924d98")]
        public partial class SignInToYourAccountAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _useanotheraccountInfo;
            RepoItemInfo _creduseridinputtextInfo;

            /// <summary>
            /// Creates a new SignInToYourAccount  folder.
            /// </summary>
            public SignInToYourAccountAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SignInToYourAccount", "/dom[@domain='login.microsoftonline.com']", parentFolder, 30000, null, false, "0d94341e-3802-43ca-ae16-72f257924d98", "")
            {
                _useanotheraccountInfo = new RepoItemInfo(this, "UseAnotherAccount", ".//table[#'use_another_account']//td/table/tbody/tr[2]/td[1]/img[@alt='Use another account']", 30000, null, "653d7c0e-d3da-45e0-a195-7f6665a9b197");
                _creduseridinputtextInfo = new RepoItemInfo(this, "CredUseridInputtext", ".//input[#'cred_userid_inputtext']", 30000, null, "2894b0e3-6ee6-4c5a-89a5-e0a8a36c9b28");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("0d94341e-3802-43ca-ae16-72f257924d98")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("0d94341e-3802-43ca-ae16-72f257924d98")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The UseAnotherAccount item.
            /// </summary>
            [RepositoryItem("653d7c0e-d3da-45e0-a195-7f6665a9b197")]
            public virtual Ranorex.ImgTag UseAnotherAccount
            {
                get
                {
                    return _useanotheraccountInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The UseAnotherAccount item info.
            /// </summary>
            [RepositoryItemInfo("653d7c0e-d3da-45e0-a195-7f6665a9b197")]
            public virtual RepoItemInfo UseAnotherAccountInfo
            {
                get
                {
                    return _useanotheraccountInfo;
                }
            }

            /// <summary>
            /// The CredUseridInputtext item.
            /// </summary>
            [RepositoryItem("2894b0e3-6ee6-4c5a-89a5-e0a8a36c9b28")]
            public virtual Ranorex.InputTag CredUseridInputtext
            {
                get
                {
                    return _creduseridinputtextInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The CredUseridInputtext item info.
            /// </summary>
            [RepositoryItemInfo("2894b0e3-6ee6-4c5a-89a5-e0a8a36c9b28")]
            public virtual RepoItemInfo CredUseridInputtextInfo
            {
                get
                {
                    return _creduseridinputtextInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}