///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CRM
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Login_module_AD_login recording.
    /// </summary>
    [TestModule("abf84815-63bb-4a96-b63c-2c6e6f6ffa13", ModuleType.Recording, 1)]
    public partial class Login_module_AD_login : ITestModule
    {
        /// <summary>
        /// Holds an instance of the CRMRepository repository.
        /// </summary>
        public static CRMRepository repo = CRMRepository.Instance;

        static Login_module_AD_login instance = new Login_module_AD_login();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Login_module_AD_login()
        {
            AD_login = "sunjeet.khokhar{LShiftKey down}@{LShiftKey up}asurequality.com";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Login_module_AD_login Instance
        {
            get { return instance; }
        }

#region Variables

        string _AD_login;

        /// <summary>
        /// Gets or sets the value of variable AD_login.
        /// </summary>
        [TestVariable("11c750a1-6e1d-455d-b6cd-18498433f7c9")]
        public string AD_login
        {
            get { return _AD_login; }
            set { _AD_login = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'https://asurequalitytest.crm6.dynamics.com/main.aspx' with browser 'chrome' in normal mode.", new RecordItemIndex(0));
            Host.Local.OpenBrowser("https://asurequalitytest.crm6.dynamics.com/main.aspx", "chrome", "", false, false, false, false, false);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SignInToYourAccount.UseAnotherAccount' at 25;27.", repo.SignInToYourAccount.UseAnotherAccountInfo, new RecordItemIndex(1));
            repo.SignInToYourAccount.UseAnotherAccount.Click("25;27");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SignInToYourAccount.CredUseridInputtext' at 24;14.", repo.SignInToYourAccount.CredUseridInputtextInfo, new RecordItemIndex(2));
            repo.SignInToYourAccount.CredUseridInputtext.Click("24;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$AD_login' with focus on 'SignInToYourAccount.CredUseridInputtext'.", repo.SignInToYourAccount.CredUseridInputtextInfo, new RecordItemIndex(3));
            repo.SignInToYourAccount.CredUseridInputtext.PressKeys(AD_login);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SignInToYourAccount.CredPasswordInputtext' at 28;7.", repo.SignInToYourAccount.CredPasswordInputtextInfo, new RecordItemIndex(4));
            repo.SignInToYourAccount.CredPasswordInputtext.Click("28;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.MicrosoftDynamicsCRMMicrosoftDynami' at 144;14.", repo.DashboardsAQCustomerServicesDashboa.MicrosoftDynamicsCRMMicrosoftDynamiInfo, new RecordItemIndex(5));
            repo.DashboardsAQCustomerServicesDashboa.MicrosoftDynamicsCRMMicrosoftDynami.Click("144;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 10s for item 'DashboardsAQCustomerServicesDashboa.MicrosoftDynamicsCRMMicrosoftDynami' to exist.", repo.DashboardsAQCustomerServicesDashboa.MicrosoftDynamicsCRMMicrosoftDynamiInfo, new ActionTimeout(10000), new RecordItemIndex(6));
            repo.DashboardsAQCustomerServicesDashboa.MicrosoftDynamicsCRMMicrosoftDynamiInfo.WaitForExists(10000);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
