///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CRM
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Search_Techone_number_in_CRM recording.
    /// </summary>
    [TestModule("5ca96adf-222a-4918-a3b6-5558b05a238b", ModuleType.Recording, 1)]
    public partial class Search_Techone_number_in_CRM : ITestModule
    {
        /// <summary>
        /// Holds an instance of the CRMRepository repository.
        /// </summary>
        public static CRMRepository repo = CRMRepository.Instance;

        static Search_Techone_number_in_CRM instance = new Search_Techone_number_in_CRM();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Search_Techone_number_in_CRM()
        {
            Tech_One_number = "864";
            Account_name = "Fonterra Australia Pty Ltd";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Search_Techone_number_in_CRM Instance
        {
            get { return instance; }
        }

#region Variables

        string _Tech_One_number;

        /// <summary>
        /// Gets or sets the value of variable Tech_One_number.
        /// </summary>
        [TestVariable("843c4587-80e9-4eb8-9bb5-519d0b30f9ad")]
        public string Tech_One_number
        {
            get { return _Tech_One_number; }
            set { _Tech_One_number = value; }
        }

        string _Account_name;

        /// <summary>
        /// Gets or sets the value of variable Account_name.
        /// </summary>
        [TestVariable("bff3e371-1ae9-4fff-9fde-efb58c42929e")]
        public string Account_name
        {
            get { return _Account_name; }
            set { _Account_name = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            // Pre-requisite - 1. Appropriate CRM AD login session active in the Chrome browser 2. No browser window opren  .
            Report.Log(ReportLevel.Info, "Website", "Pre-requisite - 1. Appropriate CRM AD login session active in the Chrome browser 2. No browser window opren  .\r\nOpening web site 'https://asurequalitytest.crm6.dynamics.com/main.aspx' with browser 'chrome' in normal mode.", new RecordItemIndex(0));
            Host.Local.OpenBrowser("https://asurequalitytest.crm6.dynamics.com/main.aspx", "chrome", "", false, false, false, false, false);
            Delay.Milliseconds(0);
            
            // This test goes to the Accounts screen , searches for an account name by entering the Tech One number and matches the Tech One number with the Account name
            Report.Log(ReportLevel.Info, "Mouse", "This test goes to the Accounts screen , searches for an account name by entering the Tech One number and matches the Tech One number with the Account name\r\nMouse Left Click item 'DashboardsAQCustomerServicesDashboa.HomeButtonImageNavTabButtonImageSandbox' at 10;13.", repo.DashboardsAQCustomerServicesDashboa.HomeButtonImageNavTabButtonImageSandboxInfo, new RecordItemIndex(1));
            repo.DashboardsAQCustomerServicesDashboa.HomeButtonImageNavTabButtonImageSandbox.Click("10;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.NavActionButtonIcon' at 64;29.", repo.DashboardsAQCustomerServicesDashboa.NavActionButtonIconInfo, new RecordItemIndex(2));
            repo.DashboardsAQCustomerServicesDashboa.NavActionButtonIcon.Click("64;29");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.Accounts' at 15;13.", repo.DashboardsAQCustomerServicesDashboa.AccountsInfo, new RecordItemIndex(3));
            repo.DashboardsAQCustomerServicesDashboa.Accounts.Click("15;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.ContentIFrame0.CrmGridFindCriteria' at 33;7.", repo.DashboardsAQCustomerServicesDashboa.ContentIFrame0.CrmGridFindCriteriaInfo, new RecordItemIndex(4));
            repo.DashboardsAQCustomerServicesDashboa.ContentIFrame0.CrmGridFindCriteria.Click("33;7");
            Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '0' with focus on 'DashboardsAQCustomerServicesDashboa.ContentIFrame0.CrmGridFindCriteria'.", repo.DashboardsAQCustomerServicesDashboa.ContentIFrame0.CrmGridFindCriteriaInfo, new RecordItemIndex(5));
            //repo.DashboardsAQCustomerServicesDashboa.ContentIFrame0.CrmGridFindCriteria.PressKeys("0");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '48' with focus on 'DashboardsAQCustomerServicesDashboa.ContentIFrame0.CrmGridFindCriteria'.", repo.DashboardsAQCustomerServicesDashboa.ContentIFrame0.CrmGridFindCriteriaInfo, new RecordItemIndex(6));
            //repo.DashboardsAQCustomerServicesDashboa.ContentIFrame0.CrmGridFindCriteria.PressKeys("48");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Tech_One_number' with focus on 'DashboardsAQCustomerServicesDashboa.ContentIFrame0.CrmGridFindCriteria'.", repo.DashboardsAQCustomerServicesDashboa.ContentIFrame0.CrmGridFindCriteriaInfo, new RecordItemIndex(7));
            repo.DashboardsAQCustomerServicesDashboa.ContentIFrame0.CrmGridFindCriteria.PressKeys(Tech_One_number);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}' with focus on 'DashboardsAQCustomerServicesDashboa.ContentIFrame0.CrmGridFindCriteria'.", repo.DashboardsAQCustomerServicesDashboa.ContentIFrame0.CrmGridFindCriteriaInfo, new RecordItemIndex(8));
            repo.DashboardsAQCustomerServicesDashboa.ContentIFrame0.CrmGridFindCriteria.PressKeys("{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.ContentIFrame0.Nobr' at 77;10.", repo.DashboardsAQCustomerServicesDashboa.ContentIFrame0.NobrInfo, new RecordItemIndex(9));
            repo.DashboardsAQCustomerServicesDashboa.ContentIFrame0.Nobr.Click("77;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.ContentIFrame0.Nobr1' at 178;8.", repo.DashboardsAQCustomerServicesDashboa.ContentIFrame0.Nobr1Info, new RecordItemIndex(10));
            repo.DashboardsAQCustomerServicesDashboa.ContentIFrame0.Nobr1.Click("178;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (title=$Account_name) on item 'DashboardsAQCustomerServicesDashboa.ContentIFrame0.Nobr1'.", repo.DashboardsAQCustomerServicesDashboa.ContentIFrame0.Nobr1Info, new RecordItemIndex(11));
            Validate.Attribute(repo.DashboardsAQCustomerServicesDashboa.ContentIFrame0.Nobr1Info, "title", Account_name);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.MicrosoftDynamicsCRMMicrosoftDynami' at 171;21.", repo.DashboardsAQCustomerServicesDashboa.MicrosoftDynamicsCRMMicrosoftDynamiInfo, new RecordItemIndex(12));
            repo.DashboardsAQCustomerServicesDashboa.MicrosoftDynamicsCRMMicrosoftDynami.Click("171;21");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.HomeButtonImageNavTabButtonImageSandbox' at 11;13.", repo.DashboardsAQCustomerServicesDashboa.HomeButtonImageNavTabButtonImageSandboxInfo, new RecordItemIndex(13));
            repo.DashboardsAQCustomerServicesDashboa.HomeButtonImageNavTabButtonImageSandbox.Click("11;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.NavActionButtonIcon' at 62;29.", repo.DashboardsAQCustomerServicesDashboa.NavActionButtonIconInfo, new RecordItemIndex(14));
            repo.DashboardsAQCustomerServicesDashboa.NavActionButtonIcon.Click("62;29");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.Accounts' at 7;2.", repo.DashboardsAQCustomerServicesDashboa.AccountsInfo, new RecordItemIndex(15));
            repo.DashboardsAQCustomerServicesDashboa.Accounts.Click("7;2");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardsAQCustomerServicesDashboa.ContentIFrame0.CrmGridClearCriteriaImg' at 10;10.", repo.DashboardsAQCustomerServicesDashboa.ContentIFrame0.CrmGridClearCriteriaImgInfo, new RecordItemIndex(16));
            repo.DashboardsAQCustomerServicesDashboa.ContentIFrame0.CrmGridClearCriteriaImg.Click("10;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AccountsAllAccountsMicrosoftDynami.Client' at 1563;11.", repo.AccountsAllAccountsMicrosoftDynami.ClientInfo, new RecordItemIndex(17));
            repo.AccountsAllAccountsMicrosoftDynami.Client.Click("1563;11");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
